# Copyright 2025 Arniiiii lg3dx6fd@gmail.com
# Distributed under the terms of the GNU General Public License v2

EAPI=8

PYTHON_COMPAT=( python3_{10..14} )

inherit cmake-multilib python-r1

MY_PV="${PV/_/.}"

DESCRIPTION="Famous Boost libraries for C++, but built via CMake, not b2"
HOMEPAGE="https://www.boost.org/"
SRC_URI="https://github.com/boostorg/boost/releases/download/boost-${MY_PV}/boost-${MY_PV}-cmake.tar.xz"
S="${WORKDIR}/boost-${MY_PV}"

LICENSE="Boost-1.0"
SLOT="0"
# This is in deep testing.
# KEYWORDS="~amd64"

# compatibility USE flags: nls, icu, bzip2, zlib, lzma, zstd, context, stacktrace, numpy
IUSE="
test

+nls
+icu
+bzip2
+zlib
+lzma
+zstd
+context
+stacktrace
+numpy

mpi
+python
static

+boost-context-fcontext
boost-context-ucontext
boost-context-winfib

+boost-locale-icu
boost-locale-iconv
boost-locale-posix
boost-locale-std
boost-locale-winapi

+boost-thread-pthread
boost-thread-win32

+boost-iostream-zlib
+boost-iostream-bzip2
+boost-iostream-lzma
+boost-iostream-zstd

+boost-stacktrace-noop
+boost-stacktrace-backtrace
boost-stacktrace-addr2line
boost-stacktrace-basic
boost-stacktrace-windbg
boost-stacktrace-windbg-cached
boost-stacktrace-from-exception
"

# sorry, if python, then numpy is not disableable.
REQUIRED_USE="
	bzip2? ( boost-iostream-bzip2 )
	!bzip2? ( !boost-iostream-bzip2 )
	zlib? ( boost-iostream-zlib )
	!zlib? ( !boost-iostream-zlib )
	lzma? ( boost-iostream-lzma )
	!lzma? ( !boost-iostream-lzma )
	zstd? ( boost-iostream-zstd )
	!zstd? ( !boost-iostream-zstd )
	icu? ( boost-locale-icu )
	context? ( ^^ (
					boost-context-fcontext
					boost-context-ucontext
					boost-context-winfib
				)
			)
	!context? (
				!boost-context-fcontext
				!boost-context-ucontext
				!boost-context-winfib

			)
	nls? ( ^^ (
			boost-locale-icu
			boost-locale-iconv
			boost-locale-posix
			boost-locale-std
			boost-locale-winapi
			)
		)
	!nls? (
			!boost-locale-icu
			!boost-locale-iconv
			!boost-locale-posix
			!boost-locale-std
			!boost-locale-winapi
		)
	stacktrace? (
				|| (
					boost-stacktrace-noop
					boost-stacktrace-backtrace
					boost-stacktrace-addr2line
					boost-stacktrace-basic
					boost-stacktrace-windbg
					boost-stacktrace-windbg-cached
					boost-stacktrace-from-exception
					)
				)
	!stacktrace? (
				!boost-stacktrace-noop
				!boost-stacktrace-backtrace
				!boost-stacktrace-addr2line
				!boost-stacktrace-basic
				!boost-stacktrace-windbg
				!boost-stacktrace-windbg-cached
				!boost-stacktrace-from-exception

				)
	boost-locale-winapi? ( static )
	^^ ( boost-thread-pthread boost-thread-win32 )
	python? ( ${PYTHON_REQUIRED_USE} )
	numpy? ( python )
	!numpy? ( numpy )
	test? ( boost-stacktrace-noop )
"

# it doesn't work that well right now
RESTRICT="test"

DEPEND="
	boost-locale-icu? ( dev-libs/icu:=[${MULTILIB_USEDEP}] )
	boost-locale-iconv? ( virtual/libiconv[${MULTILIB_USEDEP}] )
	boost-iostream-zlib? ( virtual/zlib:=[${MULTILIB_USEDEP}] )
	boost-iostream-bzip2? ( app-arch/bzip2:=[${MULTILIB_USEDEP}] )
	boost-iostream-lzma? ( app-arch/xz-utils:=[${MULTILIB_USEDEP}] )
	boost-iostream-zstd? ( app-arch/zstd:=[${MULTILIB_USEDEP}] )
	boost-stacktrace-backtrace? ( dev-libs/libbacktrace:=[${MULTILIB_USEDEP}] )
	mpi? ( virtual/mpi[${MULTILIB_USEDEP},threads] )
	python? (
		${PYTHON_DEPS}
		numpy? (
			dev-python/numpy:=[${PYTHON_USEDEP}]
		)
	)
"

RDEPEND="${DEPEND}
"

BDEPEND="
dev-build/cmake
"

# also, please, check someone this : https://www.boost.org/patches/
PATCHES=(
	"${FILESDIR}/0000_boost-1.87.0_iostreams_pkgconfig.patch"
	"${FILESDIR}/0001_debug_logs_from_cmake.patch"
)

multilib_src_configure() {
	# Gentoo users enable ccache via e.g. FEATURES=ccache or
	# other means. We don't want the build system to enable it for us.
	# sed -i -e '/find_program(CCACHE_FOUND ccache)/d' CMakeLists.txt || die

	local mycmakeargs=(
		-DBOOST_ENABLE_MPI=$(usex mpi ON OFF)
		-DBUILD_SHARED_LIBS=$(usex static true false)
		-DBOOST_IOSTREAMS_ENABLE_ZLIB=$(usex boost-iostream-zlib ON OFF)
		-DBOOST_IOSTREAMS_ENABLE_BZIP2=$(usex boost-iostream-bzip2 ON OFF)
		-DBOOST_IOSTREAMS_ENABLE_LZMA=$(usex boost-iostream-lzma ON OFF)
		-DBOOST_IOSTREAMS_ENABLE_ZSTD=$(usex boost-iostream-zstd ON OFF)
		-DBOOST_STACKTRACE_ENABLE_NOOP=$(usex boost-stacktrace-noop ON OFF)
		-DBOOST_STACKTRACE_ENABLE_BACKTRACE=$(usex boost-stacktrace-backtrace ON OFF)
		-DBOOST_STACKTRACE_ENABLE_ADDR2LINE=$(usex boost-stacktrace-addr2line ON OFF)
		-DBOOST_STACKTRACE_ENABLE_BASIC=$(usex boost-stacktrace-basic ON OFF)
		-DBOOST_STACKTRACE_ENABLE_WINDBG=$(usex boost-stacktrace-windbg ON OFF)
		-DBOOST_STACKTRACE_ENABLE_WINDBG_CACHED=$(usex boost-stacktrace-windbg-cached ON OFF)
		-DBOOST_STACKTRACE_ENABLE_FROM_EXCEPTION=$(usex boost-stacktrace-from-exception ON OFF)
		-DBUILD_TESTING=$(usex test ON OFF)

		# my default
		-DFETCHCONTENT_QUIET=OFF
		--log-level=DEBUG
	)
	if use boost-context-fcontext; then
		mycmakeargs+=( -DBOOST_CONTEXT_IMPLEMENTATION=fcontext )
	elif use boost-context-ucontext; then
		mycmakeargs+=( -DBOOST_CONTEXT_IMPLEMENTATION=ucontext )
	elif use boost-context-winfib; then
		mycmakeargs+=( -DBOOST_CONTEXT_IMPLEMENTATION=winfib )
	fi

	if use boost-locale-icu; then
		mycmakeargs+=( -DBOOST_LOCALE_ENABLE_ICU=ON )
	elif use boost-locale-iconv; then
		mycmakeargs+=( -DBOOST_LOCALE_ENABLE_ICONV=ON )
	elif use boost-locale-posix; then
		mycmakeargs+=( -DBOOST_LOCALE_ENABLE_POSIX=ON )
	elif use boost-locale-std; then
		mycmakeargs+=( -DBOOST_LOCALE_ENABLE_STD=ON )
	elif use boost-locale-winapi; then
		mycmakeargs+=( -DBOOST_LOCALE_ENABLE_WINAPI=ON )
	fi

	if use boost-thread-pthread; then
		mycmakeargs+=( -DBOOST_THREAD_THREADAPI=pthread )
	elif use boost-thread-win32; then
		mycmakeargs+=( -DBOOST_THREAD_THREADAPI=win32 )
	fi

	mycmakeargs+=(
		-DBOOST_ENABLE_PYTHON=OFF
		-DPYTHON_EXECUTABLE="no"
	)
	cmake_src_configure

	if multilib_native_use python; then
		python_configure() {
			# Set all python variables to load the correct Gentoo paths
			local mycmakeargs=(
				# this is correct, but not minimal, TODODONE: filter the args to minimal required
				"${mycmakeargs[@]}"
				# python_setup alters PATH and sets this as wrapper
				# to the correct interpreter we are building for
				-DBOOST_ENABLE_PYTHON=ON
				-DPYTHON_DEFAULT_EXECUTABLE="${EPYTHON}"
				# filter:
				-DBOOST_INCLUDE_LIBRARIES=python
			)
			cmake_src_configure
		}

		python_foreach_impl python_configure
	fi
}

multilib_src_compile() {
	cmake_src_compile
	if multilib_native_use python; then
		python_foreach_impl cmake_src_compile
	fi
}

multilib_src_test() {
	cmake_src_test
	if multilib_native_use python; then
		python_foreach_impl cmake_src_test
	fi
}

multilib_src_install() {

		MULTILIB_WRAPPED_HEADERS=(
			/usr/include/boost/accumulators/numeric/detail/function4.hpp
			/usr/include/boost/accumulators/numeric/detail/function_n.hpp
			/usr/include/boost/accumulators/statistics/rolling_mean.hpp
			/usr/include/boost/accumulators/statistics/skewness.hpp
			/usr/include/boost/accumulators/statistics/tail_mean.hpp
			/usr/include/boost/accumulators/statistics/tail_variate.hpp
			/usr/include/boost/accumulators/statistics/weighted_p_square_quantile.hpp
			/usr/include/boost/algorithm/apply_permutation.hpp
			/usr/include/boost/algorithm/cxx11/is_permutation.hpp
			/usr/include/boost/algorithm/cxx11/is_sorted.hpp
			/usr/include/boost/algorithm/sort_subrange.hpp
			/usr/include/boost/algorithm/string/detail/finder.hpp
			/usr/include/boost/algorithm/string/find.hpp
			/usr/include/boost/algorithm/string/split.hpp
			/usr/include/boost/algorithm/string/std/rope_traits.hpp
			/usr/include/boost/algorithm/string/trim.hpp
			/usr/include/boost/align/aligned_allocator_forward.hpp
			/usr/include/boost/aligned_storage.hpp
			/usr/include/boost/archive/detail/basic_iarchive.hpp
			/usr/include/boost/archive/detail/register_archive.hpp
			/usr/include/boost/archive/impl/text_wiarchive_impl.ipp
			/usr/include/boost/archive/impl/xml_iarchive_impl.ipp
			/usr/include/boost/archive/impl/xml_oarchive_impl.ipp
			/usr/include/boost/archive/iterators/base64_from_binary.hpp
			/usr/include/boost/archive/polymorphic_text_woarchive.hpp
			/usr/include/boost/archive/xml_iarchive.hpp
			/usr/include/boost/asio/associator.hpp
			/usr/include/boost/asio/buffer.hpp
			/usr/include/boost/asio/completion_condition.hpp
			/usr/include/boost/asio/default_completion_token.hpp
			/usr/include/boost/asio/detail/bind_handler.hpp
			/usr/include/boost/asio/detail/conditionally_enabled_mutex.hpp
			/usr/include/boost/asio/detail/impl/descriptor_ops.ipp
			/usr/include/boost/asio/detail/impl/dev_poll_reactor.ipp
			/usr/include/boost/asio/detail/impl/kqueue_reactor.hpp
			/usr/include/boost/asio/detail/impl/reactive_socket_service_base.ipp
			/usr/include/boost/asio/detail/impl/strand_executor_service.hpp
			/usr/include/boost/asio/detail/impl/win_iocp_io_context.ipp
			/usr/include/boost/asio/detail/impl/win_object_handle_service.ipp
			/usr/include/boost/asio/detail/io_uring_socket_send_op.hpp
			/usr/include/boost/asio/detail/is_buffer_sequence.hpp
			/usr/include/boost/asio/detail/null_thread.hpp
			/usr/include/boost/asio/detail/posix_event.hpp
			/usr/include/boost/asio/detail/posix_signal_blocker.hpp
			/usr/include/boost/asio/detail/reactive_null_buffers_op.hpp
			/usr/include/boost/asio/detail/reactive_socket_accept_op.hpp
			/usr/include/boost/asio/detail/resolve_op.hpp
			/usr/include/boost/asio/detail/socket_types.hpp
			/usr/include/boost/asio/detail/win_iocp_file_service.hpp
			/usr/include/boost/asio/detail/winrt_ssocket_service_base.hpp
			/usr/include/boost/asio/experimental/cancellation_condition.hpp
			/usr/include/boost/asio/experimental/concurrent_channel.hpp
			/usr/include/boost/asio/experimental/detail/has_signature.hpp
			/usr/include/boost/asio/impl/io_context.ipp
			/usr/include/boost/asio/impl/redirect_error.hpp
			/usr/include/boost/asio/impl/serial_port_base.ipp
			/usr/include/boost/asio/impl/system_context.hpp
			/usr/include/boost/asio/ip/basic_resolver_entry.hpp
			/usr/include/boost/asio/ip/icmp.hpp
			/usr/include/boost/asio/is_write_buffered.hpp
			/usr/include/boost/asio/local/stream_protocol.hpp
			/usr/include/boost/asio/signal_set_base.hpp
			/usr/include/boost/asio/socket_base.hpp
			/usr/include/boost/asio/ssl/detail/openssl_types.hpp
			/usr/include/boost/asio/windows/overlapped_handle.hpp
			/usr/include/boost/asio/write_at.hpp
			/usr/include/boost/asio/yield.hpp
			/usr/include/boost/assign/std.hpp
			/usr/include/boost/atomic/detail/bitwise_fp_cast.hpp
			/usr/include/boost/atomic/detail/caps_arch_msvc_x86.hpp
			/usr/include/boost/atomic/detail/core_arch_operations.hpp
			/usr/include/boost/atomic/detail/core_arch_ops_gcc_x86.hpp
			/usr/include/boost/atomic/detail/core_ops_gcc_atomic.hpp
			/usr/include/boost/atomic/detail/extra_fp_operations.hpp
			/usr/include/boost/atomic/detail/extra_fp_operations_fwd.hpp
			/usr/include/boost/atomic/detail/extra_ops_emulated.hpp
			/usr/include/boost/atomic/detail/fence_arch_operations.hpp
			/usr/include/boost/atomic/detail/float_sizes.hpp
			/usr/include/boost/atomic/detail/gcc_ppc_asm_common.hpp
			/usr/include/boost/atomic/detail/type_traits/is_enum.hpp
			/usr/include/boost/beast/core/detail/buffers_pair.hpp
			/usr/include/boost/beast/core/detail/impl/temporary_buffer.ipp
			/usr/include/boost/beast/core/detail/pcg.hpp
			/usr/include/boost/beast/core/detail/tuple.hpp
			/usr/include/boost/beast/core/detail/variant.hpp
			/usr/include/boost/beast/core/impl/buffers_adaptor.hpp
			/usr/include/boost/beast/http/basic_file_body_fwd.hpp
			/usr/include/boost/beast/http/impl/fields.hpp
			/usr/include/boost/beast/http/impl/file_body_win32.hpp
			/usr/include/boost/beast/http/impl/status.ipp
			/usr/include/boost/beast/http/message_generator_fwd.hpp
			/usr/include/boost/beast/websocket/impl/stream_impl.hpp
			/usr/include/boost/beast/websocket/teardown.hpp
			/usr/include/boost/bimap.hpp
			/usr/include/boost/bimap/container_adaptor/list_adaptor.hpp
			/usr/include/boost/bimap/container_adaptor/unordered_multiset_adaptor.hpp
			/usr/include/boost/bimap/detail/generate_relation_binder.hpp
			/usr/include/boost/bimap/detail/manage_additional_parameters.hpp
			/usr/include/boost/bimap/detail/map_view_iterator.hpp
			/usr/include/boost/bimap/multiset_of.hpp
			/usr/include/boost/bimap/relation/support/get_pair_functor.hpp
			/usr/include/boost/bimap/relation/support/opposite_tag.hpp
			/usr/include/boost/bimap/views/unordered_multimap_view.hpp
			/usr/include/boost/bimap/views/unordered_multiset_view.hpp
			/usr/include/boost/bimap/views/vector_map_view.hpp
			/usr/include/boost/callable_traits/is_rvalue_reference_member.hpp
			/usr/include/boost/charconv/detail/config.hpp
			/usr/include/boost/charconv/detail/emulated128.hpp
			/usr/include/boost/charconv/detail/fast_float/fast_table.hpp
			/usr/include/boost/charconv/to_chars.hpp
			/usr/include/boost/chrono/detail/inlined/posix/process_cpu_clocks.hpp
			/usr/include/boost/cobalt/detail/generator.hpp
			/usr/include/boost/cobalt/detail/join.hpp
			/usr/include/boost/cobalt/detail/task.hpp
			/usr/include/boost/cobalt/detail/with.hpp
			/usr/include/boost/cobalt/gather.hpp
			/usr/include/boost/cobalt/promise.hpp
			/usr/include/boost/cobalt/result.hpp
			/usr/include/boost/cobalt/spawn.hpp
			/usr/include/boost/cobalt/this_thread.hpp
			/usr/include/boost/compute/algorithm/detail/find_extrema_with_atomics.hpp
			/usr/include/boost/compute/algorithm/detail/reduce_on_gpu.hpp
			/usr/include/boost/compute/algorithm/reduce_by_key.hpp
			/usr/include/boost/compute/algorithm/sort.hpp
			/usr/include/boost/compute/config.hpp
			/usr/include/boost/compute/core.hpp
			/usr/include/boost/compute/detail/assert_cl_success.hpp
			/usr/include/boost/compute/detail/getenv.hpp
			/usr/include/boost/compute/detail/nvidia_compute_capability.hpp
			/usr/include/boost/compute/detail/read_write_single_value.hpp
			/usr/include/boost/compute/detail/vendor.hpp
			/usr/include/boost/compute/functional/atomic.hpp
			/usr/include/boost/compute/functional/convert.hpp
			/usr/include/boost/compute/functional/detail/unpack.hpp
			/usr/include/boost/compute/interop/opencv.hpp
			/usr/include/boost/compute/interop/opengl/gl.hpp
			/usr/include/boost/compute/interop/opengl/opengl_renderbuffer.hpp
			/usr/include/boost/compute/interop/qt/qimage.hpp
			/usr/include/boost/compute/interop/qt/qtcore.hpp
			/usr/include/boost/compute/iterator/constant_buffer_iterator.hpp
			/usr/include/boost/compute/memory/svm_ptr.hpp
			/usr/include/boost/compute/random.hpp
			/usr/include/boost/compute/random/threefry_engine.hpp
			/usr/include/boost/compute/system.hpp
			/usr/include/boost/compute/types/struct.hpp
			/usr/include/boost/compute/types/tuple.hpp
			/usr/include/boost/concept/detail/borland.hpp
			/usr/include/boost/config/abi/borland_suffix.hpp
			/usr/include/boost/config/compiler/clang_version.hpp
			/usr/include/boost/config/compiler/compaq_cxx.hpp
			/usr/include/boost/config/no_tr1/functional.hpp
			/usr/include/boost/config/platform/vxworks.hpp
			/usr/include/boost/config/stdlib/stlport.hpp
			/usr/include/boost/container/detail/advanced_insert_int.hpp
			/usr/include/boost/container/detail/config_begin.hpp
			/usr/include/boost/container/detail/node_pool_impl.hpp
			/usr/include/boost/container/detail/pool_common.hpp
			/usr/include/boost/container/detail/transform_iterator.hpp
			/usr/include/boost/container/pmr/global_resource.hpp
			/usr/include/boost/container/scoped_allocator_fwd.hpp
			/usr/include/boost/container/static_vector.hpp
			/usr/include/boost/container/uses_allocator_fwd.hpp
			/usr/include/boost/container_hash/detail/mulx.hpp
			/usr/include/boost/context/detail/index_sequence.hpp
			/usr/include/boost/context/fiber_ucontext.hpp
			/usr/include/boost/context/windows/protected_fixedsize_stack.hpp
			/usr/include/boost/contract/core/constructor_precondition.hpp
			/usr/include/boost/contract/detail/declspec.hpp
			/usr/include/boost/contract/detail/preprocessor/keyword/protected.hpp
			/usr/include/boost/contract/detail/static_local_var.hpp
			/usr/include/boost/contract/function.hpp
			/usr/include/boost/convert.hpp
			/usr/include/boost/convert/detail/range.hpp
			/usr/include/boost/convert/parameters.hpp
			/usr/include/boost/convert/strtol.hpp
			/usr/include/boost/core/allocator_traits.hpp
			/usr/include/boost/core/default_allocator.hpp
			/usr/include/boost/core/use_default.hpp
			/usr/include/boost/coroutine/coroutine.hpp
			/usr/include/boost/coroutine/detail/flags.hpp
			/usr/include/boost/coroutine2/detail/pull_control_block_cc.ipp
			/usr/include/boost/coroutine2/detail/pull_coroutine.hpp
			/usr/include/boost/coroutine2/detail/state.hpp
			/usr/include/boost/date_time/date_formatting.hpp
			/usr/include/boost/date_time/date_generator_parser.hpp
			/usr/include/boost/date_time/dst_transition_generators.hpp
			/usr/include/boost/date_time/gregorian/greg_duration.hpp
			/usr/include/boost/date_time/special_values_parser.hpp
			/usr/include/boost/date_time/strings_from_facet.hpp
			/usr/include/boost/date_time/time_parsing.hpp
			/usr/include/boost/describe/operators.hpp
			/usr/include/boost/detail/winapi/get_current_thread.hpp
			/usr/include/boost/detail/winapi/get_process_times.hpp
			/usr/include/boost/detail/winapi/handles.hpp
			/usr/include/boost/detail/winapi/stack_backtrace.hpp
			/usr/include/boost/dll/detail/aggressive_ptr_cast.hpp
			/usr/include/boost/dll/detail/get_mem_fn_type.hpp
			/usr/include/boost/dll/import.hpp
			/usr/include/boost/dynamic_bitset_fwd.hpp
			/usr/include/boost/endian/detail/disable_warnings.hpp
			/usr/include/boost/exception/errinfo_type_info_name.hpp
			/usr/include/boost/exception/error_info.hpp
			/usr/include/boost/exception/exception.hpp
			/usr/include/boost/fiber/detail/convert.hpp
			/usr/include/boost/fiber/detail/spinlock.hpp
			/usr/include/boost/fiber/numa/all.hpp
			/usr/include/boost/fiber/recursive_timed_mutex.hpp
			/usr/include/boost/filesystem.hpp
			/usr/include/boost/flyweight/holder_tag.hpp
			/usr/include/boost/format/alt_sstream_impl.hpp
			/usr/include/boost/format/detail/workarounds_gcc-2_95.hpp
			/usr/include/boost/format/feed_args.hpp
			/usr/include/boost/format/format_implementation.hpp
			/usr/include/boost/function_equal.hpp
			/usr/include/boost/function_types/config/compiler.hpp
			/usr/include/boost/function_types/config/config.hpp
			/usr/include/boost/function_types/detail/classifier_impl/arity10_1.hpp
			/usr/include/boost/function_types/detail/components_impl/arity30_1.hpp
			/usr/include/boost/function_types/detail/components_impl/master.hpp
			/usr/include/boost/function_types/detail/synthesize_impl/arity20_0.hpp
			/usr/include/boost/function_types/detail/synthesize_impl/arity30_1.hpp
			/usr/include/boost/function_types/is_member_function_pointer.hpp
			/usr/include/boost/function_types/is_nonmember_callable_builtin.hpp
			/usr/include/boost/functional/lightweight_forward_adapter.hpp
			/usr/include/boost/functional/overloaded_function/detail/base.hpp
			/usr/include/boost/fusion/adapted/boost_array/detail/is_sequence_impl.hpp
			/usr/include/boost/fusion/adapted/boost_array/tag_of.hpp
			/usr/include/boost/fusion/adapted/boost_tuple/detail/category_of_impl.hpp
			/usr/include/boost/fusion/adapted/mpl/detail/begin_impl.hpp
			/usr/include/boost/fusion/adapted/mpl/detail/is_view_impl.hpp
			/usr/include/boost/fusion/adapted/mpl/detail/size_impl.hpp
			/usr/include/boost/fusion/adapted/std_array/detail/at_impl.hpp
			/usr/include/boost/fusion/adapted/std_tuple/detail/convert_impl.hpp
			/usr/include/boost/fusion/adapted/std_tuple/mpl/clear.hpp
			/usr/include/boost/fusion/adapted/struct/define_struct_inline.hpp
			/usr/include/boost/fusion/adapted/struct/detail/category_of_impl.hpp
			/usr/include/boost/fusion/adapted/struct/detail/define_struct.hpp
			/usr/include/boost/fusion/adapted/struct/detail/define_struct_inline.hpp
			/usr/include/boost/fusion/adapted/struct/detail/is_sequence_impl.hpp
			/usr/include/boost/fusion/algorithm/iteration/detail/for_each.hpp
			/usr/include/boost/fusion/algorithm/query/detail/any.hpp
			/usr/include/boost/fusion/algorithm/transformation.hpp
			/usr/include/boost/fusion/algorithm/transformation/flatten.hpp
			/usr/include/boost/fusion/algorithm/transformation/transform.hpp
			/usr/include/boost/fusion/container/deque/detail/cpp03/build_deque.hpp
			/usr/include/boost/fusion/container/deque/detail/cpp03/preprocessed/as_deque20.hpp
			/usr/include/boost/fusion/container/deque/detail/cpp03/preprocessed/deque_initial_size10.hpp
			/usr/include/boost/fusion/container/deque/detail/cpp03/preprocessed/deque_keyed_values10.hpp
			/usr/include/boost/fusion/container/generation/cons_tie.hpp
			/usr/include/boost/fusion/container/generation/detail/pp_make_list.hpp
			/usr/include/boost/fusion/container/generation/detail/pp_make_map.hpp
			/usr/include/boost/fusion/container/list.hpp
			/usr/include/boost/fusion/container/list/detail/cpp03/preprocessed/list10_fwd.hpp
			/usr/include/boost/fusion/container/list/detail/deref_impl.hpp
			/usr/include/boost/fusion/container/map/detail/cpp03/preprocessed/map_fwd.hpp
			/usr/include/boost/fusion/container/set/detail/cpp03/as_set.hpp
			/usr/include/boost/fusion/container/set/detail/cpp03/preprocessed/set30.hpp
			/usr/include/boost/fusion/container/set/detail/cpp03/preprocessed/set50.hpp
			/usr/include/boost/fusion/container/vector/detail/begin_impl.hpp
			/usr/include/boost/fusion/container/vector/detail/cpp03/preprocessed/as_vector20.hpp
			/usr/include/boost/fusion/container/vector/detail/cpp03/preprocessed/vector50.hpp
			/usr/include/boost/fusion/container/vector/detail/cpp03/preprocessed/vvector20.hpp
			/usr/include/boost/fusion/container/vector/detail/cpp03/vector10.hpp
			/usr/include/boost/fusion/container/vector/detail/cpp03/vector_n_chooser.hpp
			/usr/include/boost/fusion/container/vector/detail/value_of_impl.hpp
			/usr/include/boost/fusion/container/vector/vector_iterator.hpp
			/usr/include/boost/fusion/functional/adapter.hpp
			/usr/include/boost/fusion/functional/generation.hpp
			/usr/include/boost/fusion/functional/invocation.hpp
			/usr/include/boost/fusion/functional/invocation/invoke_function_object.hpp
			/usr/include/boost/fusion/include/adapt_assoc_struct_named.hpp
			/usr/include/boost/fusion/include/algorithm.hpp
			/usr/include/boost/fusion/include/cons.hpp
			/usr/include/boost/fusion/include/container.hpp
			/usr/include/boost/fusion/include/less_equal.hpp
			/usr/include/boost/fusion/include/not_equal_to.hpp
			/usr/include/boost/fusion/include/repetitive_view.hpp
			/usr/include/boost/fusion/include/segmented_fold_until.hpp
			/usr/include/boost/fusion/include/segments.hpp
			/usr/include/boost/fusion/include/sequence.hpp
			/usr/include/boost/fusion/include/std_tuple.hpp
			/usr/include/boost/fusion/include/transform_view.hpp
			/usr/include/boost/fusion/iterator/equal_to.hpp
			/usr/include/boost/fusion/iterator/iterator_facade.hpp
			/usr/include/boost/fusion/sequence.hpp
			/usr/include/boost/fusion/sequence/comparison.hpp
			/usr/include/boost/fusion/sequence/intrinsic/at_key.hpp
			/usr/include/boost/fusion/sequence/io/detail/out.hpp
			/usr/include/boost/fusion/sequence/io/out.hpp
			/usr/include/boost/fusion/support.hpp
			/usr/include/boost/fusion/support/detail/as_fusion_element.hpp
			/usr/include/boost/fusion/tuple.hpp
			/usr/include/boost/fusion/tuple/detail/make_tuple.hpp
			/usr/include/boost/fusion/tuple/detail/preprocessed/make_tuple50.hpp
			/usr/include/boost/fusion/view/filter_view/detail/key_of_impl.hpp
			/usr/include/boost/fusion/view/filter_view/detail/size_impl.hpp
			/usr/include/boost/fusion/view/flatten_view/flatten_view.hpp
			/usr/include/boost/fusion/view/joint_view/detail/begin_impl.hpp
			/usr/include/boost/fusion/view/repetitive_view/detail/end_impl.hpp
			/usr/include/boost/fusion/view/single_view/detail/prior_impl.hpp
			/usr/include/boost/fusion/view/single_view/single_view.hpp
			/usr/include/boost/fusion/view/transform_view/detail/prior_impl.hpp
			/usr/include/boost/geometry/algorithms/closest_points.hpp
			/usr/include/boost/geometry/algorithms/covered_by.hpp
			/usr/include/boost/geometry/algorithms/crosses.hpp
			/usr/include/boost/geometry/algorithms/detail/assign_indexed_point.hpp
			/usr/include/boost/geometry/algorithms/detail/buffer/piece_border.hpp
			/usr/include/boost/geometry/algorithms/detail/disjoint/point_box.hpp
			/usr/include/boost/geometry/algorithms/detail/distance/box_to_box.hpp
			/usr/include/boost/geometry/algorithms/detail/gc_topological_dimension.hpp
			/usr/include/boost/geometry/algorithms/detail/interior_iterator.hpp
			/usr/include/boost/geometry/algorithms/detail/intersection/box_box.hpp
			/usr/include/boost/geometry/algorithms/detail/is_simple/multipoint.hpp
			/usr/include/boost/geometry/algorithms/detail/overlay/colocate_clusters.hpp
			/usr/include/boost/geometry/algorithms/detail/overlay/enrich_intersection_points.hpp
			/usr/include/boost/geometry/algorithms/detail/overlay/get_turn_info_la.hpp
			/usr/include/boost/geometry/algorithms/detail/partition.hpp
			/usr/include/boost/geometry/algorithms/detail/relate/box_areal.hpp
			/usr/include/boost/geometry/algorithms/detail/relate/multi_point_geometry.hpp
			/usr/include/boost/geometry/algorithms/detail/relate/result.hpp
			/usr/include/boost/geometry/algorithms/detail/relate/turns.hpp
			/usr/include/boost/geometry/algorithms/detail/throw_on_empty_input.hpp
			/usr/include/boost/geometry/algorithms/dispatch/is_valid.hpp
			/usr/include/boost/geometry/algorithms/for_each.hpp
			/usr/include/boost/geometry/algorithms/is_simple.hpp
			/usr/include/boost/geometry/algorithms/point_on_surface.hpp
			/usr/include/boost/geometry/algorithms/remove_spikes.hpp
			/usr/include/boost/geometry/arithmetic/infinite_line_functions.hpp
			/usr/include/boost/geometry/formulas/geographic.hpp
			/usr/include/boost/geometry/geometries/adapted/boost_variant.hpp
			/usr/include/boost/geometry/geometries/concepts/box_concept.hpp
			/usr/include/boost/geometry/geometries/concepts/geometry_collection_concept.hpp
			/usr/include/boost/geometry/geometries/point_xyz.hpp
			/usr/include/boost/geometry/geometries/polygon.hpp
			/usr/include/boost/geometry/index/adaptors/query.hpp
			/usr/include/boost/geometry/index/detail/algorithms/comparable_distance_near.hpp
			/usr/include/boost/geometry/index/detail/algorithms/content.hpp
			/usr/include/boost/geometry/index/detail/algorithms/diff_abs.hpp
			/usr/include/boost/geometry/index/detail/rtree/iterators.hpp
			/usr/include/boost/geometry/index/detail/rtree/linear/redistribute_elements.hpp
			/usr/include/boost/geometry/index/detail/rtree/visitors/children_box.hpp
			/usr/include/boost/geometry/index/detail/rtree/visitors/destroy.hpp
			/usr/include/boost/geometry/index/detail/rtree/visitors/spatial_query.hpp
			/usr/include/boost/geometry/index/distance_predicates.hpp
			/usr/include/boost/geometry/index/equal_to.hpp
			/usr/include/boost/geometry/index/parameters.hpp
			/usr/include/boost/geometry/index/predicates.hpp
			/usr/include/boost/geometry/io/wkt/wkt.hpp
			/usr/include/boost/geometry/iterators/detail/point_iterator/inner_range_type.hpp
			/usr/include/boost/geometry/iterators/point_reverse_iterator.hpp
			/usr/include/boost/geometry/multi/algorithms/area.hpp
			/usr/include/boost/geometry/multi/algorithms/detail/for_each_range.hpp
			/usr/include/boost/geometry/multi/algorithms/detail/overlay/get_turns.hpp
			/usr/include/boost/geometry/multi/algorithms/detail/sections/sectionalize.hpp
			/usr/include/boost/geometry/multi/core/tags.hpp
			/usr/include/boost/geometry/policies/relate/intersection_policy.hpp
			/usr/include/boost/geometry/srs/iau2000.hpp
			/usr/include/boost/geometry/srs/projections/constants.hpp
			/usr/include/boost/geometry/srs/projections/grids.hpp
			/usr/include/boost/geometry/srs/projections/iau2000_params.hpp
			/usr/include/boost/geometry/srs/projections/impl/pj_tsfn.hpp
			/usr/include/boost/geometry/srs/projections/par_data.hpp
			/usr/include/boost/geometry/srs/projections/proj/boggs.hpp
			/usr/include/boost/geometry/srs/projections/proj/eqdc.hpp
			/usr/include/boost/geometry/srs/projections/proj/lask.hpp
			/usr/include/boost/geometry/srs/projections/proj/lcca.hpp
			/usr/include/boost/geometry/srs/projections/proj/loxim.hpp
			/usr/include/boost/geometry/srs/projections/proj/mbtfpq.hpp
			/usr/include/boost/geometry/srs/projections/proj/moll.hpp
			/usr/include/boost/geometry/srs/projections/proj/putp6.hpp
			/usr/include/boost/geometry/srs/projections/proj/urmfps.hpp
			/usr/include/boost/geometry/srs/projections/proj/wink2.hpp
			/usr/include/boost/geometry/srs/shared_grids_std.hpp
			/usr/include/boost/geometry/strategies/azimuth/cartesian.hpp
			/usr/include/boost/geometry/strategies/cartesian/buffer_join_round_by_divide.hpp
			/usr/include/boost/geometry/strategies/cartesian/buffer_point_square.hpp
			/usr/include/boost/geometry/strategies/cartesian/centroid_bashein_detmer.hpp
			/usr/include/boost/geometry/strategies/cartesian/distance_pythagoras.hpp
			/usr/include/boost/geometry/strategies/cartesian/distance_segment_box.hpp
			/usr/include/boost/geometry/strategies/cartesian/envelope.hpp
			/usr/include/boost/geometry/strategies/cartesian/intersection.hpp
			/usr/include/boost/geometry/strategies/cartesian/point_in_point.hpp
			/usr/include/boost/geometry/strategies/closest_points/services.hpp
			/usr/include/boost/geometry/strategies/concepts/convex_hull_concept.hpp
			/usr/include/boost/geometry/strategies/covered_by.hpp
			/usr/include/boost/geometry/strategies/default_area_result.hpp
			/usr/include/boost/geometry/strategies/discrete_distance/cartesian.hpp
			/usr/include/boost/geometry/strategies/distance/comparable.hpp
			/usr/include/boost/geometry/strategies/geographic/buffer_join_miter.hpp
			/usr/include/boost/geometry/strategies/geographic/buffer_side_straight.hpp
			/usr/include/boost/geometry/strategies/geographic/distance_vincenty.hpp
			/usr/include/boost/geometry/strategies/io/cartesian.hpp
			/usr/include/boost/geometry/strategies/line_interpolate/cartesian.hpp
			/usr/include/boost/geometry/strategies/relate/geographic.hpp
			/usr/include/boost/geometry/strategies/spherical/distance_cross_track_point_box.hpp
			/usr/include/boost/geometry/strategies/spherical/envelope.hpp
			/usr/include/boost/geometry/strategy/relate.hpp
			/usr/include/boost/geometry/util/bounds.hpp
			/usr/include/boost/geometry/util/normalize_spheroidal_box_coordinates.hpp
			/usr/include/boost/geometry/util/normalize_spheroidal_coordinates.hpp
			/usr/include/boost/geometry/util/select_coordinate_type.hpp
			/usr/include/boost/geometry/util/transform_variant.hpp
			/usr/include/boost/geometry/views/box_view.hpp
			/usr/include/boost/gil/color_base.hpp
			/usr/include/boost/gil/extension/dynamic_image/apply_operation.hpp
			/usr/include/boost/gil/extension/io/png/detail/is_allowed.hpp
			/usr/include/boost/gil/extension/io/png/detail/supported_types.hpp
			/usr/include/boost/gil/extension/io/png/old.hpp
			/usr/include/boost/gil/extension/io/pnm/detail/scanline_read.hpp
			/usr/include/boost/gil/extension/io/pnm/detail/write.hpp
			/usr/include/boost/gil/extension/io/pnm/old.hpp
			/usr/include/boost/gil/extension/io/raw/detail/read.hpp
			/usr/include/boost/gil/extension/io/targa/detail/read.hpp
			/usr/include/boost/gil/extension/io/targa/detail/supported_types.hpp
			/usr/include/boost/gil/extension/numeric/algorithm.hpp
			/usr/include/boost/gil/extension/toolbox/metafunctions.hpp
			/usr/include/boost/gil/extension/toolbox/metafunctions/get_pixel_type.hpp
			/usr/include/boost/gil/io/base.hpp
			/usr/include/boost/gil/io/get_writer.hpp
			/usr/include/boost/graph/bandwidth.hpp
			/usr/include/boost/graph/chrobak_payne_drawing.hpp
			/usr/include/boost/graph/cuthill_mckee_ordering.hpp
			/usr/include/boost/graph/detail/incremental_components.hpp
			/usr/include/boost/graph/edge_connectivity.hpp
			/usr/include/boost/graph/floyd_warshall_shortest.hpp
			/usr/include/boost/graph/geodesic_distance.hpp
			/usr/include/boost/graph/graph_traits.hpp
			/usr/include/boost/graph/isomorphism.hpp
			/usr/include/boost/graph/johnson_all_pairs_shortest.hpp
			/usr/include/boost/graph/mcgregor_common_subgraphs.hpp
			/usr/include/boost/graph/property_iter_range.hpp
			/usr/include/boost/graph/property_maps/null_property_map.hpp
			/usr/include/boost/graph/sloan_ordering.hpp
			/usr/include/boost/graph/use_mpi.hpp
			/usr/include/boost/hana/adapt_adt.hpp
			/usr/include/boost/hana/bool.hpp
			/usr/include/boost/hana/concept/euclidean_ring.hpp
			/usr/include/boost/hana/core.hpp
			/usr/include/boost/hana/core/dispatch.hpp
			/usr/include/boost/hana/detail/algorithm.hpp
			/usr/include/boost/hana/detail/any_of.hpp
			/usr/include/boost/hana/detail/canonical_constant.hpp
			/usr/include/boost/hana/detail/create.hpp
			/usr/include/boost/hana/detail/has_common_embedding.hpp
			/usr/include/boost/hana/detail/operators/searchable.hpp
			/usr/include/boost/hana/drop_while.hpp
			/usr/include/boost/hana/equal.hpp
			/usr/include/boost/hana/ext/boost/fusion.hpp
			/usr/include/boost/hana/ext/boost/fusion/vector.hpp
			/usr/include/boost/hana/ext/boost/mpl.hpp
			/usr/include/boost/hana/extract.hpp
			/usr/include/boost/hana/filter.hpp
			/usr/include/boost/hana/functional/demux.hpp
			/usr/include/boost/hana/functional/fix.hpp
			/usr/include/boost/hana/functional/flip.hpp
			/usr/include/boost/hana/fwd/at.hpp
			/usr/include/boost/hana/fwd/cartesian_product.hpp
			/usr/include/boost/hana/fwd/chain.hpp
			/usr/include/boost/hana/fwd/concat.hpp
			/usr/include/boost/hana/fwd/flatten.hpp
			/usr/include/boost/hana/fwd/for_each.hpp
			/usr/include/boost/hana/fwd/front.hpp
			/usr/include/boost/hana/fwd/greater.hpp
			/usr/include/boost/hana/fwd/min.hpp
			/usr/include/boost/hana/fwd/mult.hpp
			/usr/include/boost/hana/fwd/remove.hpp
			/usr/include/boost/hana/fwd/remove_if.hpp
			/usr/include/boost/hana/fwd/tuple.hpp
			/usr/include/boost/hana/greater.hpp
			/usr/include/boost/hana/lexicographical_compare.hpp
			/usr/include/boost/hana/second.hpp
			/usr/include/boost/hana/unfold_left.hpp
			/usr/include/boost/hash2/detail/keccak.hpp
			/usr/include/boost/hash2/hash_append_fwd.hpp
			/usr/include/boost/hash2/is_endian_independent.hpp
			/usr/include/boost/hash2/is_trivially_equality_comparable.hpp
			/usr/include/boost/hash2/ripemd.hpp
			/usr/include/boost/heap/pairing_heap.hpp
			/usr/include/boost/histogram/accumulators.hpp
			/usr/include/boost/histogram/algorithm/project.hpp
			/usr/include/boost/histogram/algorithm/sum.hpp
			/usr/include/boost/histogram/axis/integer.hpp
			/usr/include/boost/histogram/axis/interval_view.hpp
			/usr/include/boost/histogram/axis/variant.hpp
			/usr/include/boost/histogram/detail/array_wrapper.hpp
			/usr/include/boost/histogram/detail/detect.hpp
			/usr/include/boost/hof/compose.hpp
			/usr/include/boost/hof/construct.hpp
			/usr/include/boost/hof/detail/delegate.hpp
			/usr/include/boost/hof/detail/unpack_tuple.hpp
			/usr/include/boost/hof/detail/unwrap.hpp
			/usr/include/boost/hof/fold.hpp
			/usr/include/boost/hof/match.hpp
			/usr/include/boost/icl/concept/joinable.hpp
			/usr/include/boost/icl/interval.hpp
			/usr/include/boost/icl/type_traits/domain_type_of.hpp
			/usr/include/boost/icl/type_traits/no_type.hpp
			/usr/include/boost/implicit_cast.hpp
			/usr/include/boost/integer/static_log2.hpp
			/usr/include/boost/interprocess/containers/list.hpp
			/usr/include/boost/interprocess/detail/min_max.hpp
			/usr/include/boost/interprocess/detail/simple_swap.hpp
			/usr/include/boost/interprocess/detail/win32_api.hpp
			/usr/include/boost/interprocess/detail/windows_intermodule_singleton.hpp
			/usr/include/boost/interprocess/indexes/null_index.hpp
			/usr/include/boost/interprocess/ipc/message_queue.hpp
			/usr/include/boost/interprocess/mem_algo/simple_seq_fit.hpp
			/usr/include/boost/interprocess/segment_manager.hpp
			/usr/include/boost/interprocess/sync/cv_status.hpp
			/usr/include/boost/interprocess/sync/posix/named_semaphore.hpp
			/usr/include/boost/interprocess/sync/shm/named_semaphore.hpp
			/usr/include/boost/interprocess/sync/spin/semaphore.hpp
			/usr/include/boost/intrusive/circular_slist_algorithms.hpp
			/usr/include/boost/intrusive/detail/algo_type.hpp
			/usr/include/boost/intrusive/detail/any_node_and_algorithms.hpp
			/usr/include/boost/intrusive/detail/default_header_holder.hpp
			/usr/include/boost/intrusive/detail/mpl.hpp
			/usr/include/boost/intrusive/detail/slist_iterator.hpp
			/usr/include/boost/intrusive/detail/workaround.hpp
			/usr/include/boost/intrusive/link_mode.hpp
			/usr/include/boost/intrusive/sgtree.hpp
			/usr/include/boost/intrusive/splaytree_algorithms.hpp
			/usr/include/boost/iostreams/code_converter.hpp
			/usr/include/boost/iostreams/detail/absolute_path.hpp
			/usr/include/boost/iostreams/detail/adapter/non_blocking_adapter.hpp
			/usr/include/boost/iostreams/detail/char_traits.hpp
			/usr/include/boost/iostreams/detail/config/fpos.hpp
			/usr/include/boost/iostreams/detail/config/limits.hpp
			/usr/include/boost/iostreams/detail/fstream.hpp
			/usr/include/boost/iostreams/detail/streambuf/chainbuf.hpp
			/usr/include/boost/iostreams/device/null.hpp
			/usr/include/boost/iostreams/get.hpp
			/usr/include/boost/iostreams/output_sequence.hpp
			/usr/include/boost/is_placeholder.hpp
			/usr/include/boost/iterator/iterator_archetypes.hpp
			/usr/include/boost/iterator/reverse_iterator.hpp
			/usr/include/boost/json/basic_parser.hpp
			/usr/include/boost/json/detail/buffer.hpp
			/usr/include/boost/json/detail/charconv/chars_format.hpp
			/usr/include/boost/json/detail/charconv/detail/fast_float/ascii_number.hpp
			/usr/include/boost/json/detail/charconv/detail/fast_float/parse_number.hpp
			/usr/include/boost/json/detail/charconv/detail/from_chars_float_impl.hpp
			/usr/include/boost/json/detail/impl/default_resource.ipp
			/usr/include/boost/json/detail/impl/stack.hpp
			/usr/include/boost/json/detail/ryu/detail/common.hpp
			/usr/include/boost/json/fwd.hpp
			/usr/include/boost/json/impl/object.hpp
			/usr/include/boost/json/impl/parser.ipp
			/usr/include/boost/json/monotonic_resource.hpp
			/usr/include/boost/lambda/closures.hpp
			/usr/include/boost/lambda/detail/member_ptr.hpp
			/usr/include/boost/lambda/detail/ret.hpp
			/usr/include/boost/leaf/common.hpp
			/usr/include/boost/local_function/aux_/preprocessor/traits/decl_/index.hpp
			/usr/include/boost/local_function/aux_/preprocessor/traits/decl_/nil.hpp
			/usr/include/boost/local_function/aux_/preprocessor/traits/decl_binds.hpp
			/usr/include/boost/local_function/detail/preprocessor/keyword/thisunderscore.hpp
			/usr/include/boost/local_function/detail/preprocessor/void_list.hpp
			/usr/include/boost/locale/boundary/facets.hpp
			/usr/include/boost/log/attributes/constant.hpp
			/usr/include/boost/log/attributes/mutable_constant.hpp
			/usr/include/boost/log/detail/default_attribute_names.hpp
			/usr/include/boost/log/detail/generate_overloads.hpp
			/usr/include/boost/log/detail/is_ostream.hpp
			/usr/include/boost/log/detail/sfinae_tools.hpp
			/usr/include/boost/log/detail/thread_id.hpp
			/usr/include/boost/log/detail/unary_function_terminal.hpp
			/usr/include/boost/log/expressions/formatters/c_decorator.hpp
			/usr/include/boost/log/expressions/keyword.hpp
			/usr/include/boost/log/expressions/predicates.hpp
			/usr/include/boost/log/keywords/auto_flush.hpp
			/usr/include/boost/log/keywords/enable_final_rotation.hpp
			/usr/include/boost/log/keywords/name.hpp
			/usr/include/boost/log/keywords/rotation_size.hpp
			/usr/include/boost/log/keywords/severity.hpp
			/usr/include/boost/log/keywords/target_file_name.hpp
			/usr/include/boost/log/sinks/bounded_fifo_queue.hpp
			/usr/include/boost/log/sinks/bounded_ordering_queue.hpp
			/usr/include/boost/log/sinks/syslog_backend.hppusr/include/boost/mpl/tag.hpp
			/usr/include/boost/log/sources/severity_channel_logger.hpp
			/usr/include/boost/log/support/std_regex.hpp
			/usr/include/boost/log/utility/functional/ends_with.hpp
			/usr/include/boost/log/utility/setup.hpp
			/usr/include/boost/log/utility/setup/from_stream.hpp
			/usr/include/boost/log/utility/type_dispatch/dynamic_type_dispatcher.hpp
			/usr/include/boost/log/utility/value_ref_fwd.hpp
			/usr/include/boost/math/ccmath/ccmath.hpp
			/usr/include/boost/math/ccmath/copysign.hpp
			/usr/include/boost/math/ccmath/ilogb.hpp
			/usr/include/boost/math/complex/acosh.hpp
			/usr/include/boost/math/distributions/bernoulli.hpp
			/usr/include/boost/math/distributions/detail/derived_accessors.hpp
			/usr/include/boost/math/distributions/find_location.hpp
			/usr/include/boost/math/distributions/non_central_chi_squared.hpp
			/usr/include/boost/math/distributions/uniform.hpp
			/usr/include/boost/math/quadrature/exp_sinh.hpp
			/usr/include/boost/math/quadrature/trapezoidal.hpp
			/usr/include/boost/math/special_functions/acosh.hpp
			/usr/include/boost/math/special_functions/detail/bessel_jy.hpp
			/usr/include/boost/math/special_functions/detail/bessel_jy_asym.hpp
			/usr/include/boost/math/special_functions/detail/bessel_kn.hpp
			/usr/include/boost/math/special_functions/detail/hypergeometric_1F1_addition_theorems_on_z.hpp
			/usr/include/boost/math/special_functions/detail/hypergeometric_1F1_bessel.hpp
			/usr/include/boost/math/special_functions/detail/hypergeometric_series.hpp
			/usr/include/boost/math/special_functions/digamma.hpp
			/usr/include/boost/math/special_functions/ellint_rc.hpp
			/usr/include/boost/math/special_functions/ellint_rg.hpp
			/usr/include/boost/math/special_functions/jacobi_elliptic.hpp
			/usr/include/boost/math/special_functions/pow.hpp
			/usr/include/boost/math/tools/color_maps.hpp
			/usr/include/boost/math/tools/detail/polynomial_horner1_10.hpp
			/usr/include/boost/math/tools/detail/polynomial_horner2_10.hpp
			/usr/include/boost/math/tools/detail/polynomial_horner2_12.hpp
			/usr/include/boost/math/tools/detail/polynomial_horner2_17.hpp
			/usr/include/boost/math/tools/detail/polynomial_horner3_6.hpp
			/usr/include/boost/math/tools/detail/rational_horner1_10.hpp
			/usr/include/boost/math/tools/detail/rational_horner1_14.hpp
			/usr/include/boost/math/tools/detail/rational_horner3_10.hpp
			/usr/include/boost/math/tools/polynomial.hpp
			/usr/include/boost/math/tools/real_cast.hpp
			/usr/include/boost/math/tools/traits.hpp
			/usr/include/boost/math_fwd.hpp
			/usr/include/boost/metaparse/change_error_message.hpp
			/usr/include/boost/metaparse/error/unpaired.hpp
			/usr/include/boost/metaparse/error/whitespace_expected.hpp
			/usr/include/boost/metaparse/foldl_reject_incomplete1.hpp
			/usr/include/boost/metaparse/foldr_reject_incomplete1.hpp
			/usr/include/boost/metaparse/get_position.hpp
			/usr/include/boost/metaparse/get_prev_char.hpp
			/usr/include/boost/metaparse/get_remaining.hpp
			/usr/include/boost/metaparse/grammar.hpp
			/usr/include/boost/metaparse/look_ahead.hpp
			/usr/include/boost/metaparse/one_char.hpp
			/usr/include/boost/metaparse/one_char_except_c.hpp
			/usr/include/boost/metaparse/string_value.hpp
			/usr/include/boost/metaparse/transform_error.hpp
			/usr/include/boost/metaparse/util/digit_to_int_c.hpp
			/usr/include/boost/metaparse/util/int_to_digit_c.hpp
			/usr/include/boost/metaparse/v1/cpp11/impl/any_of_c.hpp
			/usr/include/boost/metaparse/v1/cpp98/impl/sequence_impl.hpp
			/usr/include/boost/metaparse/v1/cpp98/impl/size.hpp
			/usr/include/boost/metaparse/v1/cpp98/repeated_one_of.hpp
			/usr/include/boost/metaparse/v1/digit_val.hpp
			/usr/include/boost/metaparse/v1/foldl_reject_incomplete1.hpp
			/usr/include/boost/metaparse/v1/fwd/accept.hpp
			/usr/include/boost/metaparse/v1/fwd/get_line.hpp
			/usr/include/boost/metaparse/v1/get_remaining.hpp
			/usr/include/boost/metaparse/v1/impl/at_c.hpp
			/usr/include/boost/metaparse/v1/impl/next_digit.hpp
			/usr/include/boost/metaparse/v1/util/digit_to_int_c.hpp
			/usr/include/boost/move/algo/move.hpp
			/usr/include/boost/move/algorithm.hpp
			/usr/include/boost/move/detail/iterator_to_raw_pointer.hpp
			/usr/include/boost/move/utility_core.hpp
			/usr/include/boost/mp11/detail/config.hpp
			/usr/include/boost/mp11/lambda.hpp
			/usr/include/boost/mp11/mpl_list.hpp
			/usr/include/boost/mp11/version.hpp
			/usr/include/boost/mpl/arg_fwd.hpp
			/usr/include/boost/mpl/assert.hpp
			/usr/include/boost/mpl/aux_/arity.hpp
			/usr/include/boost/mpl/aux_/config/adl.hpp
			/usr/include/boost/mpl/aux_/filter_iter.hpp
			/usr/include/boost/mpl/aux_/fold_pred.hpp
			/usr/include/boost/mpl/aux_/has_begin.hpp
			/usr/include/boost/mpl/aux_/has_type.hpp
			/usr/include/boost/mpl/aux_/include_preprocessed.hpp
			/usr/include/boost/mpl/aux_/msvc_eti_base.hpp
			/usr/include/boost/mpl/aux_/nttp_decl.hpp
			/usr/include/boost/mpl/aux_/preprocessed/bcc/fold_impl.hpp
			/usr/include/boost/mpl/aux_/preprocessed/bcc/greater.hpp
			/usr/include/boost/mpl/aux_/preprocessed/bcc/iter_fold_if_impl.hpp
			/usr/include/boost/mpl/aux_/preprocessed/bcc_pre590/fold_impl.hpp
			/usr/include/boost/mpl/aux_/preprocessed/bcc_pre590/greater.hpp
			/usr/include/boost/mpl/aux_/preprocessed/bcc_pre590/iter_fold_if_impl.hpp
			/usr/include/boost/mpl/aux_/preprocessed/dmc/bind.hpp
			/usr/include/boost/mpl/aux_/preprocessed/gcc/greater.hpp
			/usr/include/boost/mpl/aux_/preprocessed/msvc60/bind.hpp
			/usr/include/boost/mpl/aux_/preprocessed/msvc60/reverse_fold_impl.hpp
			/usr/include/boost/mpl/aux_/preprocessed/msvc70/bind.hpp
			/usr/include/boost/mpl/aux_/preprocessed/msvc70/less_equal.hpp
			/usr/include/boost/mpl/aux_/preprocessed/msvc70/unpack_args.hpp
			/usr/include/boost/mpl/aux_/preprocessed/mwcw/greater.hpp
			/usr/include/boost/mpl/aux_/preprocessed/no_ctps/equal_to.hpp
			/usr/include/boost/mpl/aux_/preprocessed/no_ctps/greater_equal.hpp
			/usr/include/boost/mpl/aux_/preprocessed/no_ctps/unpack_args.hpp
			/usr/include/boost/mpl/aux_/preprocessed/no_ttp/shift_left.hpp
			/usr/include/boost/mpl/aux_/preprocessed/plain/fold_impl.hpp
			/usr/include/boost/mpl/aux_/ptr_to_ref.hpp
			/usr/include/boost/mpl/aux_/push_back_impl.hpp
			/usr/include/boost/mpl/aux_/range_c/iterator.hpp
			/usr/include/boost/mpl/aux_/range_c/tag.hpp
			/usr/include/boost/mpl/back.hpp
			/usr/include/boost/mpl/char.hpp
			/usr/include/boost/mpl/erase_fwd.hpp
			/usr/include/boost/mpl/get_tag.hpp
			/usr/include/boost/mpl/inserter.hpp
			/usr/include/boost/mpl/is_placeholder.hpp
			/usr/include/boost/mpl/iterator_tags.hpp
			/usr/include/boost/mpl/key_type.hpp
			/usr/include/boost/mpl/limits/string.hpp
			/usr/include/boost/mpl/list/aux_/numbered.hpp
			/usr/include/boost/mpl/list/list0_c.hpp
			/usr/include/boost/mpl/map/aux_/erase_key_impl.hpp
			/usr/include/boost/mpl/map/aux_/has_key_impl.hpp
			/usr/include/boost/mpl/map/aux_/preprocessed/plain/map10.hpp
			/usr/include/boost/mpl/map/aux_/preprocessed/typeof_based/map30.hpp
			/usr/include/boost/mpl/modulus.hpp
			/usr/include/boost/mpl/pair_view.hpp
			/usr/include/boost/mpl/print.hpp
			/usr/include/boost/mpl/replace_if.hpp
			/usr/include/boost/mpl/set/aux_/preprocessed/plain/set40_c.hpp
			/usr/include/boost/mpl/set/aux_/tag.hpp
			/usr/include/boost/mpl/size_t.hpp
			/usr/include/boost/mpl/vector/aux_/empty.hpp
			/usr/include/boost/mpl/vector/aux_/preprocessed/plain/vector20.hpp
			/usr/include/boost/mpl/vector/aux_/preprocessed/typeof_based/vector30.hpp
			/usr/include/boost/mpl/vector/aux_/size.hpp
			/usr/include/boost/mpl/void_fwd.hpp
			/usr/include/boost/mqtt5/detail/topic_validation.hpp
			/usr/include/boost/mqtt5/impl/assemble_op.hpp
			/usr/include/boost/mqtt5/impl/read_message_op.hpp
			/usr/include/boost/mqtt5/mqtt_client.hpp
			/usr/include/boost/mqtt5/types.hpp
			/usr/include/boost/msm/back/history_policies.hpp
			/usr/include/boost/msm/back/metafunctions.hpp
			/usr/include/boost/msm/event_traits.hpp
			/usr/include/boost/msm/front/euml/stt_grammar.hpp
			/usr/include/boost/msm/mpl_graph/detail/graph_implementation_interface.ipp
			/usr/include/boost/multi_array/base.hpp
			/usr/include/boost/multi_array/range_list.hpp
			/usr/include/boost/multi_index/detail/has_tag.hpp
			/usr/include/boost/multi_index/detail/invalidate_iterators.hpp
			/usr/include/boost/multi_index/detail/is_function.hpp
			/usr/include/boost/multi_index/detail/ord_index_args.hpp
			/usr/include/boost/multi_index/detail/rnd_index_ptr_array.hpp
			/usr/include/boost/multi_index/identity_fwd.hpp
			/usr/include/boost/multi_index/key.hpp
			/usr/include/boost/multi_index/key_extractors.hpp
			/usr/include/boost/multi_index/mem_fun.hpp
			/usr/include/boost/multiprecision/detail/assert.hpp
			/usr/include/boost/multiprecision/detail/itos.hpp
			/usr/include/boost/multiprecision/detail/tables.hpp
			/usr/include/boost/multiprecision/traits/is_variable_precision.hpp
			/usr/include/boost/mysql/blob_view.hpp
			/usr/include/boost/mysql/client_errc.hpp
			/usr/include/boost/mysql/detail/connect_params_helpers.hpp
			/usr/include/boost/mysql/detail/escape_string.hpp
			/usr/include/boost/mysql/detail/execution_processor/static_results_impl.hpp
			/usr/include/boost/mysql/detail/field_impl.hpp
			/usr/include/boost/mysql/impl/column_type.ipp
			/usr/include/boost/mysql/impl/escape_string.ipp
			/usr/include/boost/mysql/impl/field_view.hpp
			/usr/include/boost/mysql/impl/field_view.ipp
			/usr/include/boost/mysql/impl/internal/byte_to_hex.hpp
			/usr/include/boost/mysql/impl/internal/connection_pool/connection_node.hpp
			/usr/include/boost/mysql/impl/internal/error/server_error_to_string.hpp
			/usr/include/boost/mysql/impl/internal/error/server_error_to_string.ipp
			/usr/include/boost/mysql/impl/internal/protocol/impl/binary_protocol.hpp
			/usr/include/boost/mysql/impl/internal/protocol/serialization.hpp
			/usr/include/boost/mysql/impl/internal/sansio/close_statement.hpp
			/usr/include/boost/mysql/impl/internal/sansio/read_some_rows_dynamic.hpp
			/usr/include/boost/mysql/mariadb_collations.hpp
			/usr/include/boost/mysql/resultset.hpp
			/usr/include/boost/mysql/row.hpp
			/usr/include/boost/nowide/detail/utf.hpp
			/usr/include/boost/numeric/conversion/bounds.hpp
			/usr/include/boost/numeric/conversion/detail/numeric_cast_traits.hpp
			/usr/include/boost/numeric/conversion/int_float_mixture_enum.hpp
			/usr/include/boost/numeric/interval/hw_rounding.hpp
			/usr/include/boost/numeric/odeint/algebra/multi_array_algebra.hpp
			/usr/include/boost/numeric/odeint/external/eigen/eigen_resize.hpp
			/usr/include/boost/numeric/odeint/external/vexcl/vexcl.hpp
			/usr/include/boost/numeric/odeint/iterator/integrate/integrate_adaptive.hpp
			/usr/include/boost/numeric/odeint/iterator/integrate/integrate_const.hpp
			/usr/include/boost/numeric/odeint/iterator/integrate/integrate_times.hpp
			/usr/include/boost/numeric/odeint/stepper/generation/generation_dense_output_runge_kutta.hpp
			/usr/include/boost/numeric/odeint/stepper/rosenbrock4_dense_output.hpp
			/usr/include/boost/numeric/odeint/tools/assert.hpp
			/usr/include/boost/numeric/odeint/util/is_pair.hpp
			/usr/include/boost/numeric/odeint/util/ublas_wrapper.hpp
			/usr/include/boost/numeric/ublas/matrix_proxy.hpp
			/usr/include/boost/numeric/ublas/matrix_vector.hpp
			/usr/include/boost/numeric/ublas/opencl.hpp
			/usr/include/boost/optional/detail/experimental_traits.hpp
			/usr/include/boost/optional/detail/optional_hash.hpp
			/usr/include/boost/optional/detail/optional_relops.hpp
			/usr/include/boost/outcome/detail/revision.hpp
			/usr/include/boost/outcome/experimental/status-code/detail/nt_code_to_generic_code.ipp
			/usr/include/boost/outcome/experimental/status-code/quick_status_code_from_enum.hpp
			/usr/include/boost/outcome/iostream_support.hpp
			/usr/include/boost/outcome/outcome_gdb.h
			/usr/include/boost/outcome/policy/base.hpp
			/usr/include/boost/outcome/policy/fail_to_compile_observers.hpp
			/usr/include/boost/parameter/aux_/default.hpp
			/usr/include/boost/parameter/aux_/is_tagged_argument.hpp
			/usr/include/boost/parameter/aux_/pack/as_parameter_requirements.hpp
			/usr/include/boost/parameter/aux_/preprocessor/convert_binary_seq.hpp
			/usr/include/boost/parameter/aux_/preprocessor/impl/argument_specs.hpp
			/usr/include/boost/parameter/aux_/preprocessor/impl/function_dispatch_tuple.hpp
			/usr/include/boost/parameter/aux_/preprocessor/is_binary.hpp
			/usr/include/boost/parameter/aux_/preprocessor/seq_enum.hpp
			/usr/include/boost/parameter/aux_/set.hpp
			/usr/include/boost/parameter/aux_/tag.hpp
			/usr/include/boost/parameter/preprocessor_no_spec.hpp
			/usr/include/boost/parser/detail/stl_interfaces/detail/pipeable_view.hpp
			/usr/include/boost/parser/transcode_view.hpp
			/usr/include/boost/pending/detail/property.hpp
			/usr/include/boost/pending/fibonacci_heap.hpp
			/usr/include/boost/pfr/detail/core_name14_disabled.hpp
			/usr/include/boost/phoenix.hpp
			/usr/include/boost/phoenix/bind/detail/cpp03/preprocessed/bind_function.hpp
			/usr/include/boost/phoenix/core/detail/cpp03/actor_operator.hpp
			/usr/include/boost/phoenix/core/detail/cpp03/actor_result_of.hpp
			/usr/include/boost/phoenix/core/detail/cpp03/preprocessed/actor_operator.hpp
			/usr/include/boost/phoenix/core/detail/cpp03/preprocessed/argument_no_predefined_30.hpp
			/usr/include/boost/phoenix/core/detail/cpp03/preprocessed/argument_predefined_50.hpp
			/usr/include/boost/phoenix/core/detail/cpp03/preprocessed/function_eval_expr_50.hpp
			/usr/include/boost/phoenix/core/is_actor.hpp
			/usr/include/boost/phoenix/core/is_value.hpp
			/usr/include/boost/phoenix/core/reference.hpp
			/usr/include/boost/phoenix/core/v2_eval.hpp
			/usr/include/boost/phoenix/object/detail/cpp03/construct_expr.hpp
			/usr/include/boost/phoenix/object/detail/cpp03/preprocessed/construct.hpp
			/usr/include/boost/phoenix/object/detail/cpp03/preprocessed/construct_eval.hpp
			/usr/include/boost/phoenix/object/detail/cpp03/preprocessed/new_eval_20.hpp
			/usr/include/boost/phoenix/object/detail/target.hpp
			/usr/include/boost/phoenix/object/dynamic_cast.hpp
			/usr/include/boost/phoenix/operator/detail/cpp03/preprocessed/mem_fun_ptr_eval_result_of_10.hpp
			/usr/include/boost/phoenix/operator/detail/define_operator.hpp
			/usr/include/boost/phoenix/operator/self.hpp
			/usr/include/boost/phoenix/scope/dynamic.hpp
			/usr/include/boost/phoenix/statement/detail/preprocessed/try_catch_eval.hpp
			/usr/include/boost/phoenix/statement/detail/preprocessed/try_catch_expression_30.hpp
			/usr/include/boost/phoenix/support/preprocessed/vector_20.hpp
			/usr/include/boost/poly_collection/detail/fixed_variant.hpp
			/usr/include/boost/poly_collection/detail/functional.hpp
			/usr/include/boost/polygon/detail/boolean_op.hpp
			/usr/include/boost/polygon/detail/polygon_sort_adaptor.hpp
			/usr/include/boost/polygon/polygon_set_traits.hpp
			/usr/include/boost/polygon/segment_traits.hpp
			/usr/include/boost/polygon/voronoi.hpp
			/usr/include/boost/pool/detail/guard.hpp
			/usr/include/boost/pool/detail/pool_construct.bat
			/usr/include/boost/predef/architecture/x86.h
			/usr/include/boost/predef/compiler/comeau.h
			/usr/include/boost/predef/compiler/gcc_xml.h
			/usr/include/boost/predef/compiler/palm.h
			/usr/include/boost/predef/hardware/simd/ppc/versions.h
			/usr/include/boost/predef/hardware/simd/x86.h
			/usr/include/boost/predef/language/cuda.h
			/usr/include/boost/predef/language/objc.h
			/usr/include/boost/predef/library/c.h
			/usr/include/boost/predef/library/std.h
			/usr/include/boost/predef/os/irix.h
			/usr/include/boost/predef/os/windows.h
			/usr/include/boost/predef/platform/mingw64.h
			/usr/include/boost/preprocessor/array/data.hpp
			/usr/include/boost/preprocessor/array/replace.hpp
			/usr/include/boost/preprocessor/array/size.hpp
			/usr/include/boost/preprocessor/comparison/greater.hpp
			/usr/include/boost/preprocessor/comparison/not_equal.hpp
			/usr/include/boost/preprocessor/control/iif.hpp
			/usr/include/boost/preprocessor/control/while.hpp
			/usr/include/boost/preprocessor/detail/limits/auto_rec_1024.hpp
			/usr/include/boost/preprocessor/facilities/limits/intercept_256.hpp
			/usr/include/boost/preprocessor/iteration/detail/local.hpp
			/usr/include/boost/preprocessor/list/detail/edg/fold_left.hpp
			/usr/include/boost/preprocessor/list/detail/limits/fold_right_512.hpp
			/usr/include/boost/preprocessor/list/for_each_product.hpp
			/usr/include/boost/preprocessor/max.hpp
			/usr/include/boost/preprocessor/min.hpp
			/usr/include/boost/preprocessor/repeat_from_to.hpp
			/usr/include/boost/preprocessor/repetition.hpp
			/usr/include/boost/preprocessor/repetition/enum_shifted.hpp
			/usr/include/boost/preprocessor/seq/limits/elem_256.hpp
			/usr/include/boost/preprocessor/seq/pop_front.hpp
			/usr/include/boost/preprocessor/seq/to_list.hpp
			/usr/include/boost/preprocessor/tuple/pop_back.hpp
			/usr/include/boost/preprocessor/tuple/rem.hpp
			/usr/include/boost/preprocessor/tuple/remove.hpp
			/usr/include/boost/preprocessor/tuple/reverse.hpp
			/usr/include/boost/preprocessor/variadic/has_opt.hpp
			/usr/include/boost/preprocessor/variadic/to_seq.hpp
			/usr/include/boost/preprocessor/variadic/to_tuple.hpp
			/usr/include/boost/process/exit_code.hpp
			/usr/include/boost/process/v1/async_system.hpp
			/usr/include/boost/process/v1/detail/handler_base.hpp
			/usr/include/boost/process/v1/detail/posix/asio_fwd.hpp
			/usr/include/boost/process/v1/detail/posix/async_handler.hpp
			/usr/include/boost/process/v1/detail/posix/is_running.hpp
			/usr/include/boost/process/v1/detail/posix/pipe_out.hpp
			/usr/include/boost/process/v1/detail/posix/wait_for_exit.hpp
			/usr/include/boost/process/v1/detail/windows/async_pipe.hpp
			/usr/include/boost/process/v1/detail/windows/basic_pipe.hpp
			/usr/include/boost/process/v1/detail/windows/null_in.hpp
			/usr/include/boost/process/v1/environment.hpp
			/usr/include/boost/process/v1/start_dir.hpp
			/usr/include/boost/process/v2/detail/process_handle_fd_or_signal.hpp
			/usr/include/boost/process/v2/detail/process_handle_windows.hpp
			/usr/include/boost/process/v2/posix/detail/close_handles.hpp
			/usr/include/boost/process/v2/windows/as_user_launcher.hpp
			/usr/include/boost/program_options/option.hpp
			/usr/include/boost/proto/context/detail/default_eval.hpp
			/usr/include/boost/proto/detail/deduce_domain.hpp
			/usr/include/boost/proto/detail/expr.hpp
			/usr/include/boost/proto/detail/extends_funop.hpp
			/usr/include/boost/proto/detail/preprocessed/and_n.hpp
			/usr/include/boost/proto/detail/template_arity.hpp
			/usr/include/boost/proto/functional.hpp
			/usr/include/boost/proto/functional/range/begin.hpp
			/usr/include/boost/proto/matches.hpp
			/usr/include/boost/proto/transform.hpp
			/usr/include/boost/proto/transform/impl.hpp
			/usr/include/boost/ptr_container/ptr_set.hpp
			/usr/include/boost/ptr_container/serialize_ptr_map.hpp
			/usr/include/boost/python.hpp
			/usr/include/boost/python/arg_from_python.hpp
			/usr/include/boost/python/args.hpp
			/usr/include/boost/python/args_fwd.hpp
			/usr/include/boost/python/back_reference.hpp
			/usr/include/boost/python/base_type_traits.hpp
			/usr/include/boost/python/bases.hpp
			/usr/include/boost/python/borrowed.hpp
			/usr/include/boost/python/call.hpp
			/usr/include/boost/python/call_method.hpp
			/usr/include/boost/python/cast.hpp
			/usr/include/boost/python/class.hpp
			/usr/include/boost/python/class_fwd.hpp
			/usr/include/boost/python/converter/arg_from_python.hpp
			/usr/include/boost/python/converter/arg_to_python.hpp
			/usr/include/boost/python/converter/arg_to_python_base.hpp
			/usr/include/boost/python/converter/as_to_python_function.hpp
			/usr/include/boost/python/converter/builtin_converters.hpp
			/usr/include/boost/python/converter/constructor_function.hpp
			/usr/include/boost/python/converter/context_result_converter.hpp
			/usr/include/boost/python/converter/convertible_function.hpp
			/usr/include/boost/python/converter/from_python.hpp
			/usr/include/boost/python/converter/implicit.hpp
			/usr/include/boost/python/converter/obj_mgr_arg_from_python.hpp
			/usr/include/boost/python/converter/object_manager.hpp
			/usr/include/boost/python/converter/pointer_type_id.hpp
			/usr/include/boost/python/converter/pyobject_traits.hpp
			/usr/include/boost/python/converter/pyobject_type.hpp
			/usr/include/boost/python/converter/pytype_function.hpp
			/usr/include/boost/python/converter/pytype_object_mgr_traits.hpp
			/usr/include/boost/python/converter/registered.hpp
			/usr/include/boost/python/converter/registered_pointee.hpp
			/usr/include/boost/python/converter/registrations.hpp
			/usr/include/boost/python/converter/registry.hpp
			/usr/include/boost/python/converter/return_from_python.hpp
			/usr/include/boost/python/converter/rvalue_from_python_data.hpp
			/usr/include/boost/python/converter/shared_ptr_deleter.hpp
			/usr/include/boost/python/converter/shared_ptr_from_python.hpp
			/usr/include/boost/python/converter/shared_ptr_to_python.hpp
			/usr/include/boost/python/converter/to_python_function_type.hpp
			/usr/include/boost/python/copy_const_reference.hpp
			/usr/include/boost/python/copy_non_const_reference.hpp
			/usr/include/boost/python/data_members.hpp
			/usr/include/boost/python/def.hpp
			/usr/include/boost/python/def_visitor.hpp
			/usr/include/boost/python/default_call_policies.hpp
			/usr/include/boost/python/detail/aix_init_module.hpp
			/usr/include/boost/python/detail/api_placeholder.hpp
			/usr/include/boost/python/detail/borrowed_ptr.hpp
			/usr/include/boost/python/detail/caller.hpp
			/usr/include/boost/python/detail/config.hpp
			/usr/include/boost/python/detail/construct.hpp
			/usr/include/boost/python/detail/convertible.hpp
			/usr/include/boost/python/detail/copy_ctor_mutates_rhs.hpp
			/usr/include/boost/python/detail/cv_category.hpp
			/usr/include/boost/python/detail/dealloc.hpp
			/usr/include/boost/python/detail/decorated_type_id.hpp
			/usr/include/boost/python/detail/decref_guard.hpp
			/usr/include/boost/python/detail/def_helper.hpp
			/usr/include/boost/python/detail/def_helper_fwd.hpp
			/usr/include/boost/python/detail/defaults_def.hpp
			/usr/include/boost/python/detail/defaults_gen.hpp
			/usr/include/boost/python/detail/dependent.hpp
			/usr/include/boost/python/detail/destroy.hpp
			/usr/include/boost/python/detail/enable_if.hpp
			/usr/include/boost/python/detail/exception_handler.hpp
			/usr/include/boost/python/detail/force_instantiate.hpp
			/usr/include/boost/python/detail/if_else.hpp
			/usr/include/boost/python/detail/indirect_traits.hpp
			/usr/include/boost/python/detail/invoke.hpp
			/usr/include/boost/python/detail/is_auto_ptr.hpp
			/usr/include/boost/python/detail/is_shared_ptr.hpp
			/usr/include/boost/python/detail/is_wrapper.hpp
			/usr/include/boost/python/detail/is_xxx.hpp
			/usr/include/boost/python/detail/make_keyword_range_fn.hpp
			/usr/include/boost/python/detail/make_tuple.hpp
			/usr/include/boost/python/detail/map_entry.hpp
			/usr/include/boost/python/detail/mpl_lambda.hpp
			/usr/include/boost/python/detail/msvc_typeinfo.hpp
			/usr/include/boost/python/detail/none.hpp
			/usr/include/boost/python/detail/not_specified.hpp
			/usr/include/boost/python/detail/nullary_function_adaptor.hpp
			/usr/include/boost/python/detail/operator_id.hpp
			/usr/include/boost/python/detail/overloads_fwd.hpp
			/usr/include/boost/python/detail/pointee.hpp
			/usr/include/boost/python/detail/prefix.hpp
			/usr/include/boost/python/detail/preprocessor.hpp
			/usr/include/boost/python/detail/python22_fixed.h
			/usr/include/boost/python/detail/python_type.hpp
			/usr/include/boost/python/detail/raw_pyobject.hpp
			/usr/include/boost/python/detail/referent_storage.hpp
			/usr/include/boost/python/detail/result.hpp
			/usr/include/boost/python/detail/scope.hpp
			/usr/include/boost/python/detail/sfinae.hpp
			/usr/include/boost/python/detail/signature.hpp
			/usr/include/boost/python/detail/string_literal.hpp
			/usr/include/boost/python/detail/target.hpp
			/usr/include/boost/python/detail/translate_exception.hpp
			/usr/include/boost/python/detail/type_list.hpp
			/usr/include/boost/python/detail/type_list_impl.hpp
			/usr/include/boost/python/detail/type_traits.hpp
			/usr/include/boost/python/detail/unwind_type.hpp
			/usr/include/boost/python/detail/unwrap_type_id.hpp
			/usr/include/boost/python/detail/unwrap_wrapper.hpp
			/usr/include/boost/python/detail/value_arg.hpp
			/usr/include/boost/python/detail/value_is_shared_ptr.hpp
			/usr/include/boost/python/detail/value_is_xxx.hpp
			/usr/include/boost/python/detail/void_ptr.hpp
			/usr/include/boost/python/detail/void_return.hpp
			/usr/include/boost/python/detail/wrap_python.hpp
			/usr/include/boost/python/detail/wrapper_base.hpp
			/usr/include/boost/python/dict.hpp
			/usr/include/boost/python/docstring_options.hpp
			/usr/include/boost/python/enum.hpp
			/usr/include/boost/python/errors.hpp
			/usr/include/boost/python/exception_translator.hpp
			/usr/include/boost/python/exec.hpp
			/usr/include/boost/python/extract.hpp
			/usr/include/boost/python/handle.hpp
			/usr/include/boost/python/handle_fwd.hpp
			/usr/include/boost/python/has_back_reference.hpp
			/usr/include/boost/python/implicit.hpp
			/usr/include/boost/python/import.hpp
			/usr/include/boost/python/init.hpp
			/usr/include/boost/python/instance_holder.hpp
			/usr/include/boost/python/iterator.hpp
			/usr/include/boost/python/list.hpp
			/usr/include/boost/python/long.hpp
			/usr/include/boost/python/lvalue_from_pytype.hpp
			/usr/include/boost/python/make_constructor.hpp
			/usr/include/boost/python/make_function.hpp
			/usr/include/boost/python/manage_new_object.hpp
			/usr/include/boost/python/module.hpp
			/usr/include/boost/python/module_init.hpp
			/usr/include/boost/python/numpy.hpp
			/usr/include/boost/python/numpy/config.hpp
			/usr/include/boost/python/numpy/dtype.hpp
			/usr/include/boost/python/numpy/internal.hpp
			/usr/include/boost/python/numpy/invoke_matching.hpp
			/usr/include/boost/python/numpy/matrix.hpp
			/usr/include/boost/python/numpy/ndarray.hpp
			/usr/include/boost/python/numpy/numpy_object_mgr_traits.hpp
			/usr/include/boost/python/numpy/scalars.hpp
			/usr/include/boost/python/numpy/ufunc.hpp
			/usr/include/boost/python/object.hpp
			/usr/include/boost/python/object/add_to_namespace.hpp
			/usr/include/boost/python/object/class.hpp
			/usr/include/boost/python/object/class_detail.hpp
			/usr/include/boost/python/object/class_metadata.hpp
			/usr/include/boost/python/object/class_wrapper.hpp
			/usr/include/boost/python/object/enum_base.hpp
			/usr/include/boost/python/object/find_instance.hpp
			/usr/include/boost/python/object/forward.hpp
			/usr/include/boost/python/object/function.hpp
			/usr/include/boost/python/object/function_doc_signature.hpp
			/usr/include/boost/python/object/function_handle.hpp
			/usr/include/boost/python/object/function_object.hpp
			/usr/include/boost/python/object/inheritance.hpp
			/usr/include/boost/python/object/inheritance_query.hpp
			/usr/include/boost/python/object/instance.hpp
			/usr/include/boost/python/object/iterator.hpp
			/usr/include/boost/python/object/iterator_core.hpp
			/usr/include/boost/python/object/life_support.hpp
			/usr/include/boost/python/object/make_holder.hpp
			/usr/include/boost/python/object/make_instance.hpp
			/usr/include/boost/python/object/make_ptr_instance.hpp
			/usr/include/boost/python/object/pickle_support.hpp
			/usr/include/boost/python/object/pointer_holder.hpp
			/usr/include/boost/python/object/py_function.hpp
			/usr/include/boost/python/object/stl_iterator_core.hpp
			/usr/include/boost/python/object/value_holder.hpp
			/usr/include/boost/python/object/value_holder_fwd.hpp
			/usr/include/boost/python/object_attributes.hpp
			/usr/include/boost/python/object_call.hpp
			/usr/include/boost/python/object_core.hpp
			/usr/include/boost/python/object_fwd.hpp
			/usr/include/boost/python/object_items.hpp
			/usr/include/boost/python/object_operators.hpp
			/usr/include/boost/python/object_protocol.hpp
			/usr/include/boost/python/object_protocol_core.hpp
			/usr/include/boost/python/object_slices.hpp
			/usr/include/boost/python/opaque_pointer_converter.hpp
			/usr/include/boost/python/operators.hpp
			/usr/include/boost/python/other.hpp
			/usr/include/boost/python/overloads.hpp
			/usr/include/boost/python/override.hpp
			/usr/include/boost/python/pointee.hpp
			/usr/include/boost/python/proxy.hpp
			/usr/include/boost/python/ptr.hpp
			/usr/include/boost/python/pure_virtual.hpp
			/usr/include/boost/python/raw_function.hpp
			/usr/include/boost/python/refcount.hpp
			/usr/include/boost/python/reference_existing_object.hpp
			/usr/include/boost/python/register_ptr_to_python.hpp
			/usr/include/boost/python/return_arg.hpp
			/usr/include/boost/python/return_by_value.hpp
			/usr/include/boost/python/return_internal_reference.hpp
			/usr/include/boost/python/return_opaque_pointer.hpp
			/usr/include/boost/python/return_value_policy.hpp
			/usr/include/boost/python/scope.hpp
			/usr/include/boost/python/self.hpp
			/usr/include/boost/python/signature.hpp
			/usr/include/boost/python/slice.hpp
			/usr/include/boost/python/slice_nil.hpp
			/usr/include/boost/python/ssize_t.hpp
			/usr/include/boost/python/stl_iterator.hpp
			/usr/include/boost/python/str.hpp
			/usr/include/boost/python/suite/indexing/container_utils.hpp
			/usr/include/boost/python/suite/indexing/detail/indexing_suite_detail.hpp
			/usr/include/boost/python/suite/indexing/indexing_suite.hpp
			/usr/include/boost/python/suite/indexing/map_indexing_suite.hpp
			/usr/include/boost/python/suite/indexing/vector_indexing_suite.hpp
			/usr/include/boost/python/tag.hpp
			/usr/include/boost/python/to_python_converter.hpp
			/usr/include/boost/python/to_python_indirect.hpp
			/usr/include/boost/python/to_python_value.hpp
			/usr/include/boost/python/tuple.hpp
			/usr/include/boost/python/type_id.hpp
			/usr/include/boost/python/with_custodian_and_ward.hpp
			/usr/include/boost/python/wrapper.hpp
			/usr/include/boost/qvm/deduce_vec.hpp
			/usr/include/boost/qvm/detail/quat_assign.hpp
			/usr/include/boost/qvm/detail/remove_const.hpp
			/usr/include/boost/qvm/detail/transp_impl.hpp
			/usr/include/boost/qvm/detail/vec_register_impl.hpp
			/usr/include/boost/qvm/gen/mat_operations4.hpp
			/usr/include/boost/qvm/lite.hpp
			/usr/include/boost/qvm/map.hpp
			/usr/include/boost/qvm/map_mat_mat.hpp
			/usr/include/boost/qvm/operations.hpp
			/usr/include/boost/qvm/quat_traits_defaults.hpp
			/usr/include/boost/qvm/vec_register.hpp
			/usr/include/boost/qvm/vec_register2.hpp
			/usr/include/boost/qvm/vec_register3.hpp
			/usr/include/boost/random.hpp
			/usr/include/boost/random/beta_distribution.hpp
			/usr/include/boost/random/cauchy_distribution.hpp
			/usr/include/boost/random/detail/enable_warnings.hpp
			/usr/include/boost/random/detail/iterator_mixin.hpp
			/usr/include/boost/random/detail/large_arithmetic.hpp
			/usr/include/boost/random/exponential_distribution.hpp
			/usr/include/boost/random/faure.hpp
			/usr/include/boost/random/subtract_with_carry.hpp
			/usr/include/boost/random/traits.hpp
			/usr/include/boost/random/uniform_real_distribution.hpp
			/usr/include/boost/range/adaptor/formatted.hpp
			/usr/include/boost/range/algorithm/copy.hpp
			/usr/include/boost/range/algorithm/equal.hpp
			/usr/include/boost/range/algorithm/fill_n.hpp
			/usr/include/boost/range/algorithm/stable_sort.hpp
			/usr/include/boost/range/algorithm_ext/insert.hpp
			/usr/include/boost/range/algorithm_ext/iota.hpp
			/usr/include/boost/range/counting_range.hpp
			/usr/include/boost/range/iterator.hpp
			/usr/include/boost/range/iterator_range.hpp
			/usr/include/boost/range/iterator_range_core.hpp
			/usr/include/boost/range/mfc_map.hpp
			/usr/include/boost/range/reverse_iterator.hpp
			/usr/include/boost/range/size.hpp
			/usr/include/boost/ratio/ratio.hpp
			/usr/include/boost/redis/detail/helper.hpp
			/usr/include/boost/redis/resp3/impl/serialization.ipp
			/usr/include/boost/regex.h
			/usr/include/boost/regex/v4/basic_regex_creator.hpp
			/usr/include/boost/regex/v4/icu.hpp
			/usr/include/boost/regex/v4/regex_token_iterator.hpp
			/usr/include/boost/regex/v5/icu.hpp
			/usr/include/boost/regex/v5/sub_match.hpp
			/usr/include/boost/safe_numerics/safe_integer_literal.hpp
			/usr/include/boost/scope/detail/header.hpp
			/usr/include/boost/scope/exception_checker.hpp
			/usr/include/boost/serialization/boost_array.hpp
			/usr/include/boost/serialization/list.hpp
			/usr/include/boost/serialization/optional.hpp
			/usr/include/boost/serialization/shared_ptr.hpp
			/usr/include/boost/serialization/slist.hpp
			/usr/include/boost/serialization/static_warning.hpp
			/usr/include/boost/serialization/std_variant.hpp
			/usr/include/boost/serialization/traits.hpp
			/usr/include/boost/signals2/detail/replace_slot_function.hpp
			/usr/include/boost/signals2/expired_slot.hpp
			/usr/include/boost/signals2/variadic_slot.hpp
			/usr/include/boost/smart_ptr/detail/deprecated_macros.hpp
			/usr/include/boost/smart_ptr/detail/local_counted_base.hpp
			/usr/include/boost/smart_ptr/detail/sp_interlocked.hpp
			/usr/include/boost/smart_ptr/detail/sp_noexcept.hpp
			/usr/include/boost/smart_ptr/detail/spinlock_pool.hpp
			/usr/include/boost/smart_ptr/detail/yield_k.hpp
			/usr/include/boost/smart_ptr/make_local_shared.hpp
			/usr/include/boost/smart_ptr/make_local_shared_object.hpp
			/usr/include/boost/smart_ptr/make_shared.hpp
			/usr/include/boost/sort/flat_stable_sort/flat_stable_sort.hpp
			/usr/include/boost/sort/insert_sort/insert_sort.hpp
			/usr/include/boost/spirit/home/classic/actor/push_back_actor.hpp
			/usr/include/boost/spirit/home/classic/attribute/typeof.hpp
			/usr/include/boost/spirit/home/classic/core.hpp
			/usr/include/boost/spirit/home/classic/core/composite/epsilon.hpp
			/usr/include/boost/spirit/home/classic/core/composite/impl/alternative.ipp
			/usr/include/boost/spirit/home/classic/core/nil.hpp
			/usr/include/boost/spirit/home/classic/core/non_terminal/grammar.hpp
			/usr/include/boost/spirit/home/classic/core/non_terminal/subrule.hpp
			/usr/include/boost/spirit/home/classic/dynamic/rule_alias.hpp
			/usr/include/boost/spirit/home/classic/dynamic/select.hpp
			/usr/include/boost/spirit/home/classic/dynamic/while.hpp
			/usr/include/boost/spirit/home/classic/phoenix/primitives.hpp
			/usr/include/boost/spirit/home/classic/phoenix/statements.hpp
			/usr/include/boost/spirit/home/classic/utility/grammar_def_fwd.hpp
			/usr/include/boost/spirit/home/classic/version.hpp
			/usr/include/boost/spirit/home/karma/action.hpp
			/usr/include/boost/spirit/home/karma/action/action.hpp
			/usr/include/boost/spirit/home/karma/detail/extract_from.hpp
			/usr/include/boost/spirit/home/karma/detail/generate_auto.hpp
			/usr/include/boost/spirit/home/karma/directive/columns.hpp
			/usr/include/boost/spirit/home/karma/string/lit.hpp
			/usr/include/boost/spirit/home/lex/argument.hpp
			/usr/include/boost/spirit/home/lex/lexer/lexertl/semantic_action_data.hpp
			/usr/include/boost/spirit/home/lex/lexer/lexertl/wrap_action.hpp
			/usr/include/boost/spirit/home/lex/lexer/support_functions.hpp
			/usr/include/boost/spirit/home/lex/lexer_type.hpp
			/usr/include/boost/spirit/home/qi/auto.hpp
			/usr/include/boost/spirit/home/qi/match_auto.hpp
			/usr/include/boost/spirit/home/qi/nonterminal/nonterminal_fwd.hpp
			/usr/include/boost/spirit/home/qi/operator.hpp
			/usr/include/boost/spirit/home/qi/operator/plus.hpp
			/usr/include/boost/spirit/home/qi/parse_attr.hpp
			/usr/include/boost/spirit/home/qi/string/detail/tst.hpp
			/usr/include/boost/spirit/home/qi/string/symbols.hpp
			/usr/include/boost/spirit/home/support/algorithm/any.hpp
			/usr/include/boost/spirit/home/support/algorithm/any_if_ns.hpp
			/usr/include/boost/spirit/home/support/char_encoding/unicode/query.hpp
			/usr/include/boost/spirit/home/support/detail/as_variant.hpp
			/usr/include/boost/spirit/home/support/detail/get_encoding.hpp
			/usr/include/boost/spirit/home/support/detail/lexer/generator.hpp
			/usr/include/boost/spirit/home/support/detail/lexer/parser/tree/sequence_node.hpp
			/usr/include/boost/spirit/home/support/detail/make_cons.hpp
			/usr/include/boost/spirit/home/support/detail/scoped_enum_emulation.hpp
			/usr/include/boost/spirit/home/support/iterators/detail/input_iterator_policy.hpp
			/usr/include/boost/spirit/home/support/iterators/multi_pass_fwd.hpp
			/usr/include/boost/spirit/home/support/utree/detail/utree_detail2.hpp
			/usr/include/boost/spirit/home/x3/auxiliary.hpp
			/usr/include/boost/spirit/home/x3/binary.hpp
			/usr/include/boost/spirit/home/x3/char/char_set.hpp
			/usr/include/boost/spirit/home/x3/core/skip_over.hpp
			/usr/include/boost/spirit/home/x3/nonterminal/debug_handler_state.hpp
			/usr/include/boost/spirit/home/x3/nonterminal/detail/rule.hpp
			/usr/include/boost/spirit/home/x3/nonterminal/simple_trace.hpp
			/usr/include/boost/spirit/home/x3/numeric/uint.hpp
			/usr/include/boost/spirit/home/x3/string/detail/string_parse.hpp
			/usr/include/boost/spirit/home/x3/support/traits/has_attribute.hpp
			/usr/include/boost/spirit/home/x3/support/traits/is_variant.hpp
			/usr/include/boost/spirit/home/x3/support/traits/optional_traits.hpp
			/usr/include/boost/spirit/home/x3/support/traits/transform_attribute.hpp
			/usr/include/boost/spirit/home/x3/support/traits/variant_has_substitute.hpp
			/usr/include/boost/spirit/home/x3/support/unused.hpp
			/usr/include/boost/spirit/home/x3/version.hpp
			/usr/include/boost/spirit/include/classic_assert.hpp
			/usr/include/boost/spirit/include/classic_chset.hpp
			/usr/include/boost/spirit/include/classic_chset_operators.hpp
			/usr/include/boost/spirit/include/classic_common.hpp
			/usr/include/boost/spirit/include/classic_difference.hpp
			/usr/include/boost/spirit/include/classic_directives.hpp
			/usr/include/boost/spirit/include/classic_escape_char_fwd.hpp
			/usr/include/boost/spirit/include/classic_exceptions.hpp
			/usr/include/boost/spirit/include/classic_exceptions_fwd.hpp
			/usr/include/boost/spirit/include/classic_iterator.hpp
			/usr/include/boost/spirit/include/classic_lazy.hpp
			/usr/include/boost/spirit/include/classic_match.hpp
			/usr/include/boost/spirit/include/classic_parse_tree_fwd.hpp
			/usr/include/boost/spirit/include/classic_symbols_fwd.hpp
			/usr/include/boost/spirit/include/classic_typeof.hpp
			/usr/include/boost/spirit/include/karma_as.hpp
			/usr/include/boost/spirit/include/karma_center_alignment.hpp
			/usr/include/boost/spirit/include/karma_format_auto.hpp
			/usr/include/boost/spirit/include/karma_lazy.hpp
			/usr/include/boost/spirit/include/karma_nonterminal.hpp
			/usr/include/boost/spirit/include/karma_omit.hpp
			/usr/include/boost/spirit/include/karma_optional.hpp
			/usr/include/boost/spirit/include/karma_right_alignment.hpp
			/usr/include/boost/spirit/include/karma_strict_relaxed.hpp
			/usr/include/boost/spirit/include/karma_upper_lower_case.hpp
			/usr/include/boost/spirit/include/phoenix1_tuples.hpp
			/usr/include/boost/spirit/include/qi_matches.hpp
			/usr/include/boost/spirit/include/support_any_if_ns_so.hpp
			/usr/include/boost/spirit/include/support_iso8859_1.hpp
			/usr/include/boost/spirit/repository/home/karma.hpp
			/usr/include/boost/spirit/repository/home/qi/primitive/advance.hpp
			/usr/include/boost/spirit/repository/home/support/subrule_context.hpp
			/usr/include/boost/spirit/repository/include/qi_confix.hpp
			/usr/include/boost/spirit/repository/include/qi_flush_multi_pass.hpp
			/usr/include/boost/spirit/repository/include/qi_primitive.hpp
			/usr/include/boost/stacktrace.hpp
			/usr/include/boost/statechart/fifo_worker.hpp
			/usr/include/boost/statechart/termination.hpp
			/usr/include/boost/swap.hpp
			/usr/include/boost/system/detail/enable_if.hpp
			/usr/include/boost/system/detail/errc.hpp
			/usr/include/boost/system/detail/error_category_impl.hpp
			/usr/include/boost/system/detail/generic_category_message.hpp
			/usr/include/boost/system/errc.hpp
			/usr/include/boost/test/auto_unit_test.hpp
			/usr/include/boost/test/data/test_case.hpp
			/usr/include/boost/test/debug.hpp
			/usr/include/boost/test/floating_point_comparison.hpp
			/usr/include/boost/test/impl/compiler_log_formatter.ipp
			/usr/include/boost/test/impl/progress_monitor.ipp
			/usr/include/boost/test/tools/assertion.hpp
			/usr/include/boost/test/tools/context.hpp
			/usr/include/boost/test/tree/test_case_template.hpp
			/usr/include/boost/test/utils/lazy_ostream.hpp
			/usr/include/boost/test/utils/runtime/cla/parser.hpp
			/usr/include/boost/test/utils/runtime/errors.hpp
			/usr/include/boost/thread.hpp
			/usr/include/boost/thread/caller_context.hpp
			/usr/include/boost/thread/concurrent_queues/sync_deque.hpp
			/usr/include/boost/thread/condition.hpp
			/usr/include/boost/thread/csbl/memory/allocator_traits.hpp
			/usr/include/boost/thread/csbl/memory/pointer_traits.hpp
			/usr/include/boost/thread/csbl/memory/scoped_allocator.hpp
			/usr/include/boost/thread/detail/lockable_wrapper.hpp
			/usr/include/boost/thread/detail/platform.hpp
			/usr/include/boost/thread/executor.hpp
			/usr/include/boost/thread/executors/work.hpp
			/usr/include/boost/thread/experimental/parallel/v1/exception_list.hpp
			/usr/include/boost/thread/futures/future_error.hpp
			/usr/include/boost/thread/futures/future_error_code.hpp
			/usr/include/boost/thread/locks.hpp
			/usr/include/boost/thread/pthread/pthread_helpers.hpp
			/usr/include/boost/thread/win32/mfc_thread_init.hpp
			/usr/include/boost/timer/config.hpp
			/usr/include/boost/tti/detail/denum.hpp
			/usr/include/boost/tti/detail/dlambda.hpp
			/usr/include/boost/tti/detail/dstatic_mem_fun_template.hpp
			/usr/include/boost/tti/gen/has_function_gen.hpp
			/usr/include/boost/tti/gen/has_template_gen.hpp
			/usr/include/boost/tti/gen/member_type_gen.hpp
			/usr/include/boost/type_erasure/call.hpp
			/usr/include/boost/type_erasure/derived.hpp
			/usr/include/boost/type_erasure/detail/get_signature.hpp
			/usr/include/boost/type_erasure/placeholder_of.hpp
			/usr/include/boost/type_index/detail/stl_register_class.hpp
			/usr/include/boost/type_traits/add_const.hpp
			/usr/include/boost/type_traits/add_pointer.hpp
			/usr/include/boost/type_traits/broken_compiler_spec.hpp
			/usr/include/boost/type_traits/conjunction.hpp
			/usr/include/boost/type_traits/detail/detector.hpp
			/usr/include/boost/type_traits/detail/is_member_function_pointer_cxx_03.hpp
			/usr/include/boost/type_traits/has_complement.hpp
			/usr/include/boost/type_traits/has_greater.hpp
			/usr/include/boost/type_traits/has_less_equal.hpp
			/usr/include/boost/type_traits/has_minus.hpp
			/usr/include/boost/type_traits/has_negate.hpp
			/usr/include/boost/type_traits/has_nothrow_constructor.hpp
			/usr/include/boost/type_traits/has_virtual_destructor.hpp
			/usr/include/boost/type_traits/is_abstract.hpp
			/usr/include/boost/type_traits/is_bounded_array.hpp
			/usr/include/boost/type_traits/is_member_object_pointer.hpp
			/usr/include/boost/type_traits/is_polymorphic.hpp
			/usr/include/boost/type_traits/is_reference.hpp
			/usr/include/boost/type_traits/is_trivially_copyable.hpp
			/usr/include/boost/type_traits/is_unscoped_enum.hpp
			/usr/include/boost/type_traits/remove_cv.hpp
			/usr/include/boost/typeof/std/streambuf.hpp
			/usr/include/boost/typeof/typeof.hpp
			/usr/include/boost/units/base_dimension.hpp
			/usr/include/boost/units/base_units/angle/arcminute.hpp
			/usr/include/boost/units/base_units/angle/steradian.hpp
			/usr/include/boost/units/base_units/imperial/gallon.hpp
			/usr/include/boost/units/base_units/imperial/inch.hpp
			/usr/include/boost/units/base_units/information/shannon.hpp
			/usr/include/boost/units/base_units/metric/liter.hpp
			/usr/include/boost/units/base_units/si/kilogram.hpp
			/usr/include/boost/units/base_units/si/second.hpp
			/usr/include/boost/units/base_units/us/cup.hpp
			/usr/include/boost/units/base_units/us/mil.hpp
			/usr/include/boost/units/detail/utility.hpp
			/usr/include/boost/units/is_dimensionless_quantity.hpp
			/usr/include/boost/units/limits.hpp
			/usr/include/boost/units/physical_dimensions/acceleration.hpp
			/usr/include/boost/units/physical_dimensions/frequency.hpp
			/usr/include/boost/units/physical_dimensions/length.hpp
			/usr/include/boost/units/physical_dimensions/molar_heat_capacity.hpp
			/usr/include/boost/units/physical_dimensions/stress.hpp
			/usr/include/boost/units/systems/abstract.hpp
			/usr/include/boost/units/systems/cgs/wavenumber.hpp
			/usr/include/boost/units/systems/si/conductance.hpp
			/usr/include/boost/units/systems/si/wavenumber.hpp
			/usr/include/boost/unordered/concurrent_node_map.hpp
			/usr/include/boost/unordered/concurrent_node_set_fwd.hpp
			/usr/include/boost/unordered/detail/fca.hpp
			/usr/include/boost/unordered/detail/mulx.hpp
			/usr/include/boost/unordered/unordered_flat_set.hpp
			/usr/include/boost/unordered_map.hpp
			/usr/include/boost/unordered_set.hpp
			/usr/include/boost/url/detail/params_iter_impl.hpp
			/usr/include/boost/url/detail/string_view.hpp
			/usr/include/boost/url/grammar/lut_chars.hpp
			/usr/include/boost/url/impl/params_base.hpp
			/usr/include/boost/url/params_ref.hpp
			/usr/include/boost/url/rfc/authority_rule.hpp
			/usr/include/boost/url/rfc/query_rule.hpp
			/usr/include/boost/url/rfc/sub_delim_chars.hpp
			/usr/include/boost/url/scheme.hpp
			/usr/include/boost/url/string_view.hpp
			/usr/include/boost/url/url.natvis
			/usr/include/boost/utility.hpp
			/usr/include/boost/utility/explicit_operator_bool.hpp
			/usr/include/boost/uuid/name_generator.hpp
			/usr/include/boost/uuid/random_generator.hpp
			/usr/include/boost/variant/recursive_wrapper.hpp
			/usr/include/boost/vmd/assert_is_array.hpp
			/usr/include/boost/vmd/assert_is_number.hpp
			/usr/include/boost/vmd/detail/identifier_concat.hpp
			/usr/include/boost/vmd/detail/is_seq.hpp
			/usr/include/boost/vmd/detail/is_type.hpp
			/usr/include/boost/vmd/detail/match_identifier.hpp
			/usr/include/boost/vmd/detail/recurse/equal/equal_headers.hpp
			/usr/include/boost/vmd/detail/sequence_common.hpp
			/usr/include/boost/vmd/detail/sequence_to_list.hpp
			/usr/include/boost/vmd/empty.hpp
			/usr/include/boost/vmd/is_unary.hpp
			/usr/include/boost/vmd/seq/remove.hpp
			/usr/include/boost/vmd/seq/to_array.hpp
			/usr/include/boost/wave/cpplexer/re2clex/cpp_re2c_lexer.hpp
			/usr/include/boost/wave/grammars/cpp_has_include_grammar.hpp
			/usr/include/boost/wave/util/cpp_include_paths.hpp
			/usr/include/boost/wave/util/cpp_iterator.hpp
			/usr/include/boost/weak_ptr.hpp
			/usr/include/boost/winapi/detail/cast_ptr.hpp
			/usr/include/boost/winapi/memory.hpp
			/usr/include/boost/winapi/thread.hpp
			/usr/include/boost/xpressive/detail/core/finder.hpp
			/usr/include/boost/xpressive/detail/core/matcher/attr_end_matcher.hpp
			/usr/include/boost/xpressive/detail/core/matcher/mark_begin_matcher.hpp
			/usr/include/boost/xpressive/detail/core/matcher/repeat_begin_matcher.hpp
			/usr/include/boost/xpressive/detail/core/matcher/string_matcher.hpp
			/usr/include/boost/xpressive/detail/core/results_cache.hpp
			/usr/include/boost/xpressive/detail/core/sub_match_vector.hpp
			/usr/include/boost/xpressive/detail/static/placeholders.hpp
			/usr/include/boost/xpressive/detail/static/static.hpp
			/usr/include/boost/xpressive/detail/utility/algorithm.hpp
			/usr/include/boost/xpressive/detail/utility/boyer_moore.hpp
			/usr/include/boost/xpressive/regex_traits.hpp
			/usr/include/boost/yap/detail/algorithm.hpp
			/usr/include/boost/yap/yap.hpp

			)

	cmake_src_install
	if multilib_native_use python; then
		python_foreach_impl cmake_src_install
		python_foreach_impl python_optimize
	fi
}
